### ISSUE TITLE
Implementation of password expiration feature

### ISSUE THREAD

**Issue by GiorgiaMenozzi** [2amigos/yii2-usuario#102]
It would be nice to have the chance to set the maximum password duration time. 
If the password is expired the user should access only the password change page.  
And also it would be really great to have a sort of warning (by mail maybe) some days before the expiration date.

**Comment by tonydspaniard** [comment]
I agree... lets add this as part of the tasks :) Thank you @GiorgiaMenozzi

**Comment by maxxer** [comment]
Doing some work on my repo, if you have some spare time to have a look...

**Comment by maxxer** [comment]
@tonydspaniard I've pushed some commits on my branch to address most of the issues. Can you have a look at them when you have time? thanks

**Comment by tonydspaniard** [comment]
@maxxer would be nice if you could do a PR. I'll more than happy to review it.

**Comment by maxxer** [comment]
this can be closed!

**Comment by maxxer** [comment]
Do you think you can make a minor release which includes the changes so far?

**Comment by tonydspaniard** [comment]
@maxxer sure
