### ISSUE TITLE
Consolidate strings for two factor auth

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#103]
While updating the translation I found out there are several different ways of outputting *two factor*: 
* Two Factor Authentication
* Two-Factor Authentication
* Two-factor auth
* Two-factor authorization 

I'd suggest to change most of the strings to *2FA*, to make it shorter and uniform across the app.

**Comment by tonydspaniard** [comment]
I agree

**Comment by maxxer** [comment]
I'll try to do that myself

**Comment by tonydspaniard** [comment]
re #105
