### ISSUE TITLE
Why did you move away from yii2 module structure?

### ISSUE THREAD

**Issue by philippfrenzel** [2amigos/yii2-usuario#11]
Hi, is their a special reason while you move away from the standard module structure?
E.g. no more views?

Thanks Philipp

**Comment by tonydspaniard** [comment]
Hi @philippfrenzel 

if you look carefully, I haven't moved away from the standard module structure. Check where the views is located: https://github.com/2amigos/yii2-usuario/tree/master/src/User/resources 

What I did is to move away from the namespace naming and thats for a personal taste. Is like naming my classes under a specific namespace with a suffix, that way helps me understand what is actually that class and avoid the need to make aliases in case there is a name conflict (ie `/Service/User` vs `/Model/User`) 

Yii is highly flexible and in fact, there are recommendations but not really standards per se. A developer can organize its code in any way he wishes to. An example of that is our `yii2-app-usuario-template`: https://github.com/2amigos/yii2-app-template (here with this module enabled https://github.com/2amigos/yii2-app-usuario-template )

**Comment by philippfrenzel** [comment]
Hey, thanks for the explanation! I just wanted to understand the logic behind as I wanna learn a bit more about code organisation  - makes a lot sense to me now... The difference between the module from dektrium to yours was that obvious, that I had to ask! Thanks for taking your time!
Cheers Philipp
