### ISSUE TITLE
Unable to disable flash messages in \Da\User\Service\PasswordRecoveryService

### ISSUE THREAD

**Issue by tekord** [2amigos/yii2-usuario#110]
I have custom layout where I print all flash messages. I don't want to get flash message after password recovery, but it is impossible to do now. Module class has `enableFlashMessages` property, but it checks only in view file _alert, not in \Da\User\Service\PasswordRecoveryService class. So, I always get flash message which is not desired.

I think service classes must check if flash messages are enabled in module.

**Comment by tonydspaniard** [comment]
I agree

**Comment by maxxer** [comment]
this has been fixed

**Comment by tonydspaniard** [comment]
Thanks @maxxer
