### ISSUE TITLE
Fix migration for PostgreSQL

### ISSUE THREAD

**Issue by MKiselev** [2amigos/yii2-usuario#111]
### What steps will reproduce the problem?
Apply migrations on PostgreSQL DBMS

### What is the expected result?
Evrething ok.

### What do you get instead?
```
Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "auth_tf_enabled" is of type boolean but default expression is of type integer
```
Because on line https://github.com/2amigos/yii2-usuario/blob/master/src/User/Migration/m000000_000006_add_two_factor_fields.php#L21 used `0` as default value instead `false`

**Comment by MKiselev** [comment]
@tonydspaniard please make release after merge. :)

**Comment by tonydspaniard** [comment]
@MKiselev I'll do... Thanks!

**Comment by MKiselev** [comment]
@tonydspaniard we need release)
Can you do minor or patch release?
Thank you)

**Comment by tonydspaniard** [comment]
@MKiselev sure

**Comment by tonydspaniard** [comment]
@MKiselev done
