### ISSUE TITLE
Auth via some social network fail with pg db

### ISSUE THREAD

**Issue by Dezinger** [2amigos/yii2-usuario#115]
### What steps will reproduce the problem?

Auth via social network

### What is the expected result?

Success auth.

### What do you get instead?

```sql
exception 'PDOException' with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character varying = integer
LINE 1: ...t" WHERE ("provider"='vkontakte') AND ("client_id"=123456)
```

Pgsql fail with type convertion string != int

**Comment by tonydspaniard** [comment]
Thanks @Dezinger !
