### ISSUE TITLE
Ensure dabilite commits are incorporated into yii2-usuario

### ISSUE THREAD

**Issue by thyseus** [2amigos/yii2-usuario#12]
Hey !

great to see dektrium evolve in the yii2-usuario project. About 2 months ago a fork of dektrium was started called dabilite. It already has some bugfixes (28 commits ahead):

https://github.com/dektrium/yii2-user/compare/master...dabilite:master

I would love to abandon dabilite when these changes and improvements are incorporated into yii2-usuario. 
Would it be possible for one of you to review these changes?

Also see https://github.com/dabilite/yii2-user/issues/23 where we discuss this issue.

There should be one, great, and maintained user management module for yii2. Possible sometime a "official" one. I think yii2-usuario has the best potential to get there sometime :-)

**Comment by tonydspaniard** [comment]
@thyseus sure please, point me to the changes you wish to include and lets discuss it further!

**Comment by tonydspaniard** [comment]
@thyseus Let's start writing those issues that will require the integration of those commits. Thanks for such compliments.

**Comment by tonydspaniard** [comment]
@thyseus already agreed to your suggestion. Closing this issue, expecting to see your proposals on separated tickets. Thanks.
