### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by faenir** [2amigos/yii2-usuario#125]
Recovery form -> empty  email -> submit:
> TypeError: Argument 1 passed to Da\User\Service\PasswordRecoveryService::sendMail() must be an instance of Da\User\Model\User, null given, called in ..\vendor\2amigos\yii2-usuario\src\User\Service\PasswordRecoveryService.php on line 53 and defined in ..\vendor\2amigos\yii2-usuario\src\User\Traits\MailAwareTrait.php:36

I think need add validation [here](https://github.com/2amigos/yii2-usuario/blob/f0915a284a5dc8a538235b601609b08e2a66b1a3/src/User/Controller/RecoveryController.php#L97) like a [RegistrationController::register()](https://github.com/2amigos/yii2-usuario/blob/f0915a284a5dc8a538235b601609b08e2a66b1a3/src/User/Controller/RegistrationController.php#L101), and check other places without non-ajax validation.

` if ($form->load(Yii::$app->request->post()) && $form->validate()) {`

**Comment by tonydspaniard** [comment]
You are correct @faenir

**Comment by faenir** [comment]
#128

**Comment by tonydspaniard** [comment]
Fixed! Thanks @faenir
