### ISSUE TITLE
Profile can't be updated because timezone validation fails

### ISSUE THREAD

**Issue by fwerner13** [2amigos/yii2-usuario#13]
### What steps will reproduce the problem?

1. Goto `user/settings`
2. Click save

### What is the expected result?

Profile should be saved. 

### What do you get instead?

Validation error "Time zone is not valid"

I think line 75 in `src/User/Model/Profile.php`

```php
if ($this->make(TimeZoneValidator::class, [$this->{$attribute}])->validate()) {
```

should be

```php
if ($this->make(TimeZoneValidator::class, [$this->{$attribute}])->validate() === false) {
```

**Comment by tonydspaniard** [comment]
@fwerner13 Thank you very much for your feedback!
