### ISSUE TITLE
Make qrcode-library optional

### ISSUE THREAD

**Issue by tekord** [2amigos/yii2-usuario#131]
Today I updated old project with usuario and got error:

2amigos/qrcode-library 1.1.2 requires ext-gd * -> the requested PHP extension gd is missing from your system

I can't setup the required extension so I unable to install new version of usuario. You should make qrcode-library library as optional.

**Comment by tonydspaniard** [comment]
Is a good idea... Will update it

**Comment by cronfy** [comment]
Is there anything complex? If it's just about moving 2amigos/qrcode-library to `suggest` section of composer.json, I can file a PR tomorrow.

**Comment by maxxer** [comment]
It depends if we want to just throw exception in case the dependency is missing or if we should add  some code logic to check if the library is not installed

**Comment by maxxer** [comment]
I've pushed the requirement in my repo, will merge soon
