### ISSUE TITLE
IMPORTANT READ!

### ISSUE THREAD

**Issue by tonydspaniard** [2amigos/yii2-usuario#140]
The next couple of months I am currently under a lot of stress due to very tied milestones. I would like to apologize for not being able to handle the requests and issue responses as fast as I would like to. 

Please, be patient. I'll do my best to get back to enhance this library asap.

Best

**Comment by maxxer** [comment]
Time to find a co-maintainer! :P

**Comment by tonydspaniard** [comment]
@maxxer if you could take my place while away due to work. You are more than welcome.

**Comment by tonydspaniard** [comment]
@maxxer Thank you very much. I'll add you as maintainer so you can help me out, as I am currently on a very busy schedule with highly important projects and I cannot deliver as much as I can.

**Comment by tonydspaniard** [comment]
No Thank you @maxxer
