### ISSUE TITLE
Contributor workflow - advice needed!

### ISSUE THREAD

**Issue by ajmedway** [2amigos/yii2-usuario#158]
Hi guys, sorry but I am not used to using Github at all (I use Bitbucket and Sourcetree professionally) but I do like this project and DO wish to contribute. However, I cannot see the best workflow for contributing here.

Here is my issue:

- I have a fork of this project already: https://github.com/ajmedway/yii2-usuario
- My fork is now behind the upstream, i.e. 'This branch is 1 commit ahead, 52 commits behind 2amigos:master.'
- I need to update my fork / basically do a hard reset to 2amigos/yii2-usuario:master / do a pull request so that is it synced with the other contributions/I have all of the commits made since I forked
- THERE IS NO BUTTON/METHOD IN GITHUB TO DO THIS! https://github.com/isaacs/github/issues/121

I do not have much time to mess around with local copies etc. I simply wish to use the Github website interface to handle this, adding code from experimental changes I make/test on a composer-installed instance in my vendor directory on my dev app (where I am developing a real client project). Do I really need to delete my fork and re-fork each time I wish to contribute to achieve this?

https://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381

Thanks, Alec

**Comment by ajmedway** [comment]
Also, I don't seem to be able to add labels to issues on this project. Why is this?

**Comment by maxxer** [comment]
Typically you create your own fork. You create a new branch and create a PR.

To keep your fork up to date you add a remote with the upstream repo url (usually I call it `upstream`) and then `git merge upstream/master`. Done, you're up to date. You can start a new branch from here and code.

I don't think this can be performed only via GitHub interface, you need to mess with `git` commands! :) 

Labels and some other administration tasks are available only to owner and developers/contributor of the project. 

Better ask for help in some chat or support forum than *talking* on an issue.

**Comment by ajmedway** [comment]
Yes sorry this is perhaps not the place - anyhow I have installed Github Desktop and seem to have a workflow now - I see that @tonydspaniard has already managed to incorporate some of my changes so I will aim to make some more efficient contributions going forward. Thanks for the help.
