### ISSUE TITLE
Password change error: `DateTime::__construct(): Failed to parse time string (1518777402) at position 8 (0): Unexpected character`

### ISSUE THREAD

**Issue by ajmedway** [2amigos/yii2-usuario#159]
### What steps will reproduce the problem?

- Upgrade to latest version (1.1.3) and install migration on instance with existing users.
- Login as admin role user with administrator permissions.
- Attempt to change a user's password.

### What is the expected result?

The password is changed and success message displayed.

### What do you get instead?

> DateTime::__construct(): Failed to parse time string (1518777402) at position 8 (0): Unexpected character

![image](https://user-images.githubusercontent.com/1861604/36306797-4b5b62b6-1311-11e8-956c-ec40fcb7ccfe.png)

**Comment by maxxer** [comment]
The date doesn't seem to be null, instead it's 1518777402! In fact running `php -r '$a = new \DateTime(1518777402);'` on the command line returns the same error! 

 I'll look at it asap

**Comment by maxxer** [comment]
It has probably been fixed in #154. @tonydspaniard sorry but another minor release might be needed

**Comment by ajmedway** [comment]
Yes I presumed it was a null field issue initially as I had pre-existing users and the migration set field default value to null - but then took a closer look, it indeed was setting the value in the model initially... and yes I can confirm that it was fixed in #154 - this works in php 5.6 and 7.1:

`php -r '$a = new \DateTime("@1518777402");'`

**Comment by ajmedway** [comment]
@maxxer / @tonydspaniard - what needs to be done to have the fix in #154 come through composer with the following version constraint in my composer.json require section?

`"2amigos/yii2-usuario": "~1.0"`

For now I am using the following constraint:

`"2amigos/yii2-usuario": "@dev"`

Not ideal.

**Comment by tonydspaniard** [comment]
@ajmedway i'll make a new patched version.

**Comment by tonydspaniard** [comment]
done

**Comment by ajmedway** [comment]
Thanks!
