### ISSUE TITLE
Advice needed: i18n translations

### ISSUE THREAD

**Issue by ajmedway** [2amigos/yii2-usuario#160]
Hi, I see that there is a `User/resources/i18n/` directory that contains a package of php-file translation dictionaries and a config file. But what are we supposed to do with this? What command/workflow to actually implement custom translations in our apps? Presumable we copy somewhere and set the path in the `'components' => ['i18n' => ['translations'` config?

Any advice gratefully received!

Thanks, Alec

**Comment by maxxer** [comment]
It's automatically registered in the application [i18n](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html) component  at [Bootstrap.php](https://github.com/2amigos/yii2-usuario/blob/master/src/User/Bootstrap.php#L187)

**Comment by ajmedway** [comment]
@maxxer Thanks for your reply. Ok, I can see that, however where should our custom overrides of these i18n files reside? How do we actually implement the translations? I mean, we *could* just edit message source vendor files to add our translations, but of course we shouldn't ever modify vendor files for obvious reasons.

Looking at the bootstrap method concerned:

```
    protected function initTranslations(Application $app)
    {
        if (!isset($app->get('i18n')->translations['usuario*'])) {
            $app->get('i18n')->translations['usuario*'] = [
                'class' => PhpMessageSource::class,
                'basePath' => __DIR__ . '/resources/i18n',
                'sourceLanguage' => 'en-US',
            ];
        }
    }
```

This sets the `basePath` as the vendor files `/resources/i18n` directory. In order to implement custom overrides of the translation message sources, e.g. in `@app/messages/usuario` it appears that I would need to override this bootstrap method, or use dependancy injection to do so? Or do we use file mapping http://www.yiiframework.com/doc-2.0/yii-i18n-phpmessagesource.html#$fileMap-detail ? Or have I blindly missed something obvious (quite possible!)?

Any advice gratefully received!

Thanks, Alec

**Comment by maxxer** [comment]
I did [this](https://lorenzo.mile.si/2017/11/yii2-quick-tip-overriding-core-translations/) for Yii core messages, check if it can be applied to extensions too

**Comment by ajmedway** [comment]
@maxxer that is an elegant solution for extending translations, I will probably use this pattern in some projects! Thanks.

**Comment by ajmedway** [comment]
OK, I have found a solution to my requirements (using i18n component for string customisation to GB English)... I will post my solution here for posterity in case it is helpful to anyone.

Firstly I added this to my application config:

```
$config = [
    'components' => [
        'i18n' => [
            'translations' => [
                'usuario*' => [
                    'class' => 'yii\i18n\PhpMessageSource',
                    'basePath' => '@app/messages/usuario',
                    'sourceLanguage' => 'en-US',
                ],
            ],
        ],
    ],
    'language' => 'en-GB',
    'sourceLanguage' => 'en-US',
];
```

I then copied the [i18n config file](https://github.com/2amigos/yii2-usuario/blob/master/src/User/resources/i18n/config.php) from the module vendor files to my custom i18n messages path, i.e. `@app/messages/usuario`. I then modified my custom config for my purposes, i.e. removed all other unnecessary locales and only using `en-GB` like so:

```
return [
    'sourcePath' => \Yii::getAlias('@vendor/2amigos/yii2-usuario/src/User'),
    'messagePath' => \Yii::getAlias('@app/messages/usuario'),
    'languages' => [
        'en-GB',
    ],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => true,
    'removeUnused' => false,
    'only' => ['*.php'],
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
    ],
    'format' => 'php',
];
```

As per the docs I ran the message command, like so:

`./yii message messages/usuario/i18n/config.php`

This gave me a new en-GB directory and usuario.php skeleton message source that I could then add my tranloations to. Working well for me, given my requirements.
