### ISSUE TITLE
There is no way to remember a user with two-factor authentication

### ISSUE THREAD

**Issue by DAGpro** [2amigos/yii2-usuario#161]
Hello! Tell me please, when you turn on two-factor authorization, the ability to remember the authorization of the user is missed or so provided? (translate)
controller security/login
![](https://files.gitter.im/2amigos/yii2-usuario/brRI/2018-02-17_19-45-20.png)

controller security/confirm
![](https://files.gitter.im/2amigos/yii2-usuario/JMbR/2018-02-17_19-47-12.png)

rememberMe? :)

**Comment by tonydspaniard** [comment]
When there is a `two-auth`, the remember me shouldn't be an option. That should be forcefully required at all times.

**Comment by maxxer** [comment]
Why you say that? IMHO 2FA is an enhancement on the authentication phase, it shouldn't change the behavior of the session when authenticated, isn't it?

**Comment by DAGpro** [comment]
Understood thanks!
I thought this would be left to the developer's discretion, to allow the user to remember himself or not.

**Comment by tonydspaniard** [comment]
@maxxer is to remember after your session has been finished. Check all the cryptocurrencies sites. Is a pain but thats the way it is :)
