### ISSUE TITLE
How can I create a administrator user, or add admin role??

### ISSUE THREAD

**Issue by alexsantm** [2amigos/yii2-usuario#163]
### What steps will reproduce the problem?
I installed the module correctly, but I want to admin the rest of the modules (users, rules, roles). In fact, I created a first user normally and It worked, but I want to go to users view, I have Forbidden (#403) error. 
The migration was OK. My question is how can I add administrator role to my first user????

**Comment by maxxer** [comment]
Did you set the `administrators` parameter with your username in [configuration options](http://yii2-usuario.readthedocs.io/en/latest/installation/configuration-options/)?

**Comment by alexsantm** [comment]
Thanks for your reply..!!! No, I didnt. Could you explain me where can I configurate that (maybe in web.php,) and if you can write an example?? thanks a lot

**Comment by tonydspaniard** [comment]
@alexsantm http://yii2-usuario.readthedocs.io/en/latest/installation/console-commands/ you can create users by role too.

**Comment by alexsantm** [comment]
Thanks for your reply...!!! You were right, I will create a new admin user using the commands. I am building the menu view, using the standar code. I have the next error: Getting unknown property: yii\web\User::displayName yii2....Do you know how to display the user name in menu???

**Comment by tonydspaniard** [comment]
> Do you know how to display the user name in menu???

Should be as easy as when you get the user.
