### ISSUE TITLE
Argument 1 passed to Da\User\Controller\SecurityController::authenticate() must be an instance of Da\User\Contracts\AuthClientInterface, instance of yii\authclient\clients\Google given

### ISSUE THREAD

**Issue by imtiazmahbub** [2amigos/yii2-usuario#167]
### What steps will reproduce the problem?
Yii2 version: 2.0.14
PHP 7.1
```
    'components' => [
      // .... more lines
        'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
                'google' => [
                    'class' => 'yii\authclient\clients\Google',
                    'clientId' => 'xxxxx',
                    'clientSecret' => 'xxxxx-',
                ],
                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook',
                    'clientId' => 'xxxxx',
                    'clientSecret' => 'xxxxx',
                ],
                // etc.
            ],
        ],
```
### What is the expected result?
After authentication with google, it redirects to authorized redirect URL:
https://.....example.com/user/security/auth?authclient=google
And user is logged into the website

### What do you get instead?
```
TypeError
Argument 1 passed to Da\User\Controller\SecurityController::authenticate() must be an instance of Da\User\Contracts\AuthClientInterface, instance of yii\authclient\clients\Google given
```

![image](https://user-images.githubusercontent.com/7385976/37254407-7b0dc0ae-2567-11e8-8d01-65f212a46af7.png)

**Comment by maxxer** [comment]
The exception is quite explanatory, remote url fopen is disabled in your php configuration.

@tonydspaniard what do you think? Retain it as is and label as a configuration problem or handle unavailability of this feature and [fallback to curl](http://www.christianschenk.org/blog/php-curl-allow-url-fopen/)?

**Comment by imtiazmahbub** [comment]
Sorry, wrong image. That was before I enabled allow_url_fopen. Below screenshot is the new one that represents the issue.

![image](https://user-images.githubusercontent.com/7385976/37309001-bea09532-2669-11e8-920b-781b1a1b81c5.png)

**Comment by maxxer** [comment]
According to [the  manual](http://yii2-usuario.readthedocs.io/en/latest/helpful-guides/social-network-authentication/) the configuration components must use `Da\User\AuthClient\*` classes. You're using Yii's core ones

**Comment by imtiazmahbub** [comment]
Thank you very much @maxxer 
It skipped my eyes.  Thanks for the excellent support.
