### ISSUE TITLE
Make ids as unsigned integer

### ISSUE THREAD

**Issue by tekord** [2amigos/yii2-usuario#18]
Primary key for user table has integer type. It cannot be negative (does not make any sense), so why not to make this field as unsigned integer?

**Comment by tonydspaniard** [comment]
Thanks for bringing up this @tekord . As you know the migrations that come with the extension rely on its structure to work properly, but that doesn't mean you cannot make personal updates to it that would not affect its functionality.

**Comment by tekord** [comment]
@tonydspaniard I made new migrations, is it worth to make PR? Migrations will drop foreign keys, changes data types and creates foreign keys back. I'm worried about how these migrations can affect projects in which there are tables linked to the user table with foreign key, we can't change data type of these foreign keys.

**Comment by tonydspaniard** [comment]
@tekord I think the module should only contain general use migrations. On another note, I think we should probably create migrations for different drivers and they separated by a folder. For example: 

```
Da\Migration\MySql\... 
Da\Migration\SqlServer\... 
```
You get the idea

**Comment by tekord** [comment]
@tonydspaniard hi, Antonio! This is old topic, but want to clarify. You wrote:

> Edit: for custom migrations, simply copy the migrations to your migrations folder, remove the namespaces, make your changes and thats it (remember to not set migrations namespace to the user)

If I copy migrations from the project then I have to check each usuario's release if there is a new migration which I have to copy to my project. Seems not good solution. Any ideas how to override usuario's migrations?
