### ISSUE TITLE
`UserEvent::EVENT_AFTER_CREATE` event `User` object missing profile relation

### ISSUE THREAD

**Issue by ajmedway** [2amigos/yii2-usuario#181]
### What steps will reproduce the problem?

Create an event like so:

    Event::on(User::class, UserEvent::EVENT_AFTER_CREATE, function (UserEvent $event) {

        $user = $event->getUser();
        echo '<pre>';
        echo '$user->profile ' . print_r($user->profile, true);
        echo '</pre>';
        echo var_dump($user->profile);
        die('here');
    }

Then go to the admin area and create a user.

### What is the expected result?

The user is created with profile relation present, as indeed we see that after save the models are linked in `Da\User\Model\User`

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if ($insert && $this->profile === null) {
            $profile = $this->make(Profile::class);
            $profile->link('user', $this);
        }
    }

### What do you get instead?

`$user->profile` is `null`

**Comment by ajmedway** [comment]
Some notes...

- Tried adding `$profile->save();` after `$profile->link('user', $this);`
- Tried moving the `Da\User\Service\UserCreateService` event trigger for `UserEvent::EVENT_AFTER_CREATE` to occur after `$transaction->commit();`

But not resolved the issue.

**Comment by tonydspaniard** [comment]
@ajmedway the problem is that you use the `User::class` and the event is launched on the `AdminController::class`: https://github.com/2amigos/yii2-usuario/blob/master/src/User/Controller/AdminController.php#L135

There are no events launched on the `User::class`: https://github.com/2amigos/yii2-usuario/blob/master/src/User/Model/User.php#L121
