### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#185]
Two registration tests are failing on Travis, while they pass when executed locally.

**Comment by Eseperio** [comment]
The problem is that `$container->set()` is not working to change settings.

```
 \Yii::$container->set(Module::className(), [
            'enableEmailConfirmation' => false,
            'generatePasswords' => true,
        ]);
```
This works:
```php
  Yii::$app->getModule('user')->generatePasswords = true;
  Yii::$app->getModule('user')->enableEmailConfirmation = false;
```

**Comment by maxxer** [comment]
Thank you very much.

Out of curiosity, why the first isn't working? It should, isn't it?

**Comment by maxxer** [comment]
PHP5.6 is still failing for memory

**Comment by Eseperio** [comment]
[Practical Usage - Default](https://www.yiiframework.com/doc/guide/2.0/en/concept-di-container#practical-usage)

As in the example:
> Note: Properties given in the widget call will always override the definition in the DI container. Even if you specify an array, e.g. 'options' => ['id' => 'mypager'] these will not be merged with other options but replace them.
