### ISSUE TITLE
Login with facebook failed of missing username

### ISSUE THREAD

**Issue by kmergen** [2amigos/yii2-usuario#191]
Want to use facebook login with facebook test-user.
facebook client username is null.
Therfore I cannot create an account out of the box.

What is the best workarround?

![image](https://user-images.githubusercontent.com/1640101/41670607-0c68f644-74b5-11e8-8c2d-40cedf17d949.png)

### Cannot create account because there is no username

**Comment by maxxer** [comment]
Looks very  similar to   #130

**Comment by tonydspaniard** [comment]
@kmergen I recommend you to work on a strategy similar to #222, where  you set the username to the email  of the user. Normally, the username in many systems that work with social accounts work this way. I personally think, future versions of this module should work with emails only.
