### ISSUE TITLE
GDPR string translations

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#198]
**call for translations**

As I merged GDPR patch (thank you very much @Eseperio) and I'd like to make a new release, I'm calling translators to update messages.

I've updated all the message files in 0d06d4812ba6, you just need to pull and make a PR. Many thanks everyone.

I cited everyone I found in the git log. I see many people contributed to the same language: in order not to make the same job twice I invite everyone to post here their intention to translate a language, so efforts can be joined instead of wasted. 

@quique 
@EvgenyOrekhov 
@Dezinger 
@gugoan 
@jkmssoft 
@bizley
@mrbig00 
@faenir 
@tekord 
@thyseus 
@TonisOrmisson

**Comment by bizley** [comment]
I'll do PL.

**Comment by quique** [comment]
I'll do ES.

On Fri, Jul 13, 2018 at 10:02 AM, Bizley <notifications@github.com> wrote:
> I'll do PL.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Nothing is enough for the man to whom enough is too little.
 - Ἐπίκουρος

**Comment by maxxer** [comment]
ES and PL done!

**Comment by mrbig00** [comment]
I'll do RO

**Comment by TonisOrmisson** [comment]
Working on ET

**Comment by gugoan** [comment]
Work on pt-BR

**Comment by tonydspaniard** [comment]
@quique @bizley @gugoan @mrbig00 @maxxer please guys, add your credits on the CHANGELOG 👍

**Comment by mrbig00** [comment]
@tonydspaniard In the next few days I'm super occupied with a project release into production, so I was rushing a bit :)

Thanks @maxxer, I owe you a beer :beer:

**Comment by tonydspaniard** [comment]
@mrbig00 I am very busy the past few months due to a crypto currency exchange project. But will get back to it. I have LOTS to thank to @maxxer, more than a 🍺 . Also to the great community that keeps the extension up to date.

**Comment by maxxer** [comment]
@mrbig00 any idea when you will be able to make RO and HU? thanks

**Comment by mrbig00** [comment]
hi @maxxer probably this weekend

**Comment by Dezinger** [comment]
RU done

**Comment by Wautvda** [comment]
NL done

**Comment by maxxer** [comment]
Thanks everyone! I should have mentioned everyone in the changelog, if I've missed someone please let me know or issue a PR!
thanks again
