### ISSUE TITLE
Hey. how to connect the expansion?

### ISSUE THREAD

**Issue by DmitroChemniy** [2amigos/yii2-usuario#2]

**Comment by resurtm** [comment]
@DmitroChemniy, please check the following documentation page: http://yii2-usuario.readthedocs.io/en/latest/installation/advanced-application-template/

Also note the extension is still under heavy development. We're going to release it very soon (I guess 1—3 weeks, not more).

I'm closing this issue as I think I've answered your question. ;-)

**Comment by DmitroChemniy** [comment]
yes I read it, but "how to use login and sign up forms" link does not work

**Comment by ricar2ce** [comment]
How install the module

**Comment by tonydspaniard** [comment]
@DmitroChemniy slowly slowly I am writing the documentation. I expect to finish it by the end of the  next week: http://yii2-usuario.readthedocs.io/en/latest/ 

I am sorry for the delay but I am quite busy and the documentation that is required is quite long. I'll do my best to finish it all by the end of the next week.

**Comment by tonydspaniard** [comment]
@DmitroChemniy documentation done... hope it helps
