### ISSUE TITLE
Migration sql syntax fix

### ISSUE THREAD

**Issue by Dezinger** [2amigos/yii2-usuario#213]
### What steps will reproduce the problem?
Update migration.
PostgreSQL not support AFTER column syntax.

### What do you get instead?
Fail

> add column last_login_ip string(45) DEFAULT NULL AFTER last_login_at to table {{%user}} ...ERROR:  syntax error at or near "AFTER" at character 65

**Comment by Dezinger** [comment]
PostgreSQL not support AFTER column syntax

**Comment by maxxer** [comment]
thank you very much for your PR!
