### ISSUE TITLE
Option to resend welcome email/password reset

### ISSUE THREAD

**Issue by Wautvda** [2amigos/yii2-usuario#218]
It would be nice to have an option where the admin forces a password reset or can just resend the welcome email.

In my case it will be due to the fact that the users will be loaded through the import directly in the database (yes not conventional way, but more handy then adding 200+ users by hand). And they'll get activated one by one when the admin want them to (yes, manual action).

Right now I have to disable password reset just to be able to send the password reset as admin. Which should be available when allowAdminPasswordRecovery is set to true (which would be the most reasonable).

PR with the altered suggested allowAdminPasswordRecovery to be attached.

**Comment by tonydspaniard** [comment]
Can you provide a merge request and I'll merge it? Unfortunately, I do not have much time...

**Comment by Wautvda** [comment]
I've added the documentation update to PR !221 where I made some translation updates (had problem with creating branches).
As for resending the welcome email: I've found a workaround for my project. I now have an API endpoint which allows me to create new users. That way they get inserted in the "regular" way and get an welcome email.
