### ISSUE TITLE
email as username

### ISSUE THREAD

**Issue by ivan-cc** [2amigos/yii2-usuario#222]
How can I use only email instead of username?

Such an option is available at Login, but not when registering and editing the profile.

**Comment by mrbig00** [comment]
You can easily override your registration form, to generate a  username for the user, for example `md5()` the email, and after that you can hide the username field and mark them unsafe to prevent editing.

**Comment by maxxer** [comment]
I usually override the model and in `beforeSave` and `afterFind` assign to the username field the email value. 

then you still need to override views as well (or translations) to display *email* instead of *username*

**Comment by moneyadmin** [comment]
I added the _login_ field and use it to fill in the _email_ and _username_ fields.
I did this:
`<?php

namespace common\models;
use Da\User\Model\User as BaseUser;
class User extends BaseUser
{
    public $login;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return array_merge(
            [
                'loginTrim' => ['login', 'filter', 'filter' => 'trim'],
                'loginRequired' => ['login', 'required', 'on' => ['register', 'create', 'connect', 'update']],
                 'usernameSetval' => ['username', 'filter', 'filter' => function($att){return $this->login;}],
                 'emailSetval' => ['email', 'filter', 'filter' => function($att){return $this->login;}],
            ],
            parent::rules()
        );
    }
}`

**Comment by tonydspaniard** [comment]
Thanks for showing what you did @ivan-cc. Closing this ticket and labelled as `how-to`.
