### ISSUE TITLE
Not having a reaction if case of request to reset password for non-existing email.

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#238]
### What steps will reproduce the problem?
try `user/recovery/request` functional
for `any@email.com` who not a email of existing users

### What is the expected result?
any message like 
https://www.nvidia.com/en-us/account/forgot-password/#
"FORGOT PASSWORD
An email with instructions to create a new password has been sent to any@email.com if it is associated with an NVIDIA account.
Your existing password has not been changed.

LOG IN"

### What do you get instead?

Nothing. Code 200 and show form. Try again dear bruteforcer!

Inside: Throw a `\RuntimeException` and do nothing / not catch it for displaying anything. 

https://github.com/2amigos/yii2-usuario/blob/bd691ec9bb42ce02b875a277e1d670297128457c/src/User/Service/PasswordRecoveryService.php#L47-L49

https://github.com/2amigos/yii2-usuario/blob/bd691ec9bb42ce02b875a277e1d670297128457c/src/User/Service/PasswordRecoveryService.php#L71-L75

**Comment by tonydspaniard** [comment]
@bscheshirwork Thank you for your feedback: 

- about the bruteforcing, we didn't want to implement any captcha functionality to allow the user to override and use whatever logic he wishes. 
- about the service firing an error, is for loggin purposes only, when returning false is the controller that should react to it and do whatever the developer wishes by overriding the controller action.

**Comment by bscheshirwork** [comment]
> about the service firing an error, is for loggin purposes only, when returning false is the controller that should react to it and do whatever the developer wishes by overriding the controller action.

So... How about add this functional into controller action (withid default implementaton by show message like example from nvidea)? 

https://github.com/2amigos/yii2-usuario/blob/23b95160547be5ecdd671581373e9ca071bbb774/src/User/Controller/RecoveryController.php#L105-L115

something like this 
```php
            if ($this->make(PasswordRecoveryService::class, [$form->email, $mailService])->run()) {
                $this->trigger(FormEvent::EVENT_AFTER_REQUEST, $event);
            }

            return $this->render(
                '/shared/message',
                [
                    'title' => Yii::t('usuario', 'An email with instructions to create a new password has been sent to {email} if it is associated with an {appName} account. Your existing password has not been changed.'),
                    'module' => $this->module,
                ]
            );
```

IMHO 90% people will not redefine this module controller action.

**Comment by bscheshirwork** [comment]
Thanks!

**Comment by maxxer** [comment]
Thank you for providing PR!
