### ISSUE TITLE
we need tell more about 2fa in stock. 

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#244]
### What steps will reproduce the problem?

```
composer install 2amigos/yii2-usuario @dev
composer show 2amigos/yii2-usuario

requires (dev)
codeception/codeception *
codeception/specify ^0.4.3
codeception/verify ^0.3.1
friendsofphp/php-cs-fixer ^2.3
phpmd/phpmd @stable
squizlabs/php_codesniffer *

suggests
2amigos/2fa-library Needed if you want to enable 2 Factor Authentication. Require version ^1.0
2amigos/qrcode-library Needed if you want to enable 2FA with QR Code generation. Require version ^1.1
```

### What do you get instead?

Some common functional use `suggests` library. I'm not sure about this:
https://github.com/2amigos/yii2-usuario/blob/6aaa687e8155f922c51e32e0a8890f4260130760/src/User/Form/LoginForm.php#L14
This is legal? :smile_cat: 

In this case look like separated functional
https://github.com/2amigos/yii2-usuario/blob/6aaa687e8155f922c51e32e0a8890f4260130760/src/User/Service/TwoFactorQrCodeUriGeneratorService.php#L14-L16

https://github.com/2amigos/yii2-usuario/blob/6aaa687e8155f922c51e32e0a8890f4260130760/src/User/Validator/TwoFactorCodeValidator.php#L14-L15

**Comment by tonydspaniard** [comment]
@bscheshirwork you are correct at the loginForm level. This is an issue that must be corrected.
