### ISSUE TITLE
Different codestyle for GDPR; look like error

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#246]
### What is the expected result?
```php
    public $enableGdprCompliance = false;
    public $gdprPrivacyPolicyUrl = null;
    public $gdprExportProperties = ...
    public $gdprAnonymPrefix = 'GDPR';
```
or
```php
    public $enableGDPRCompliance = false;
    public $GDPRPrivacyPolicyUrl = null;
    public $GDPRExportProperties = ...
    public $GDPRAnonymPrefix = 'GDPR';
```
### What do you get instead?
https://github.com/2amigos/yii2-usuario/blob/23b95160547be5ecdd671581373e9ca071bbb774/src/User/Module.php#L22-L58

note: we have `BC broken` if this functional in future
(if 1.5.0 have been released yet within current code style)

>1.5.0 - Work in progress
Ehn #187: Add GDPR features (Eseperio)

**Comment by tonydspaniard** [comment]
@Eseperio ?

**Comment by Eseperio** [comment]
GDPR is an acronym for General Data Protection Regulation. That is why it is all in uppercase.

**Comment by bscheshirwork** [comment]
What about next chapter after your "acronym"?

@Eseperio you logic totally not inconsistent :suspect:  

You use other acronyms in CamelCase. And all is ok. 

For example you `GDPRprivacyPolicyUrl` contain two different style

Uniform Resource Locator, URL

So... I think we need use yii-friendly style in this case (acronym in CamelCase like other word)

**Comment by maxxer** [comment]
I'd have done like Eseperio, but your arguments are valid 😉

**Comment by Eseperio** [comment]
@bscheshirwork You are right. There is no reason to make it uppercase. @maxxer what can we do? has been released or is only in dev-master branch?  I think we should let this as it is and change it for  the new structure #236 .

**Comment by bscheshirwork** [comment]
I can see add this functional in "work in progress" chapter of changelog...
