### ISSUE TITLE
Cannot add permission into a role

### ISSUE THREAD

**Issue by minhnguyenerp** [2amigos/yii2-usuario#25]
### What steps will reproduce the problem?
In the RBAC management, I can create permissions and roles. I saw that each permission can have its own child permissions and each role can have its own child roles. But I can not find the way to add permission into a role

**Comment by tonydspaniard** [comment]
@minhnguyenerp working on it....

**Comment by tonydspaniard** [comment]
@minhnguyenerp getting in there: 
![image](https://user-images.githubusercontent.com/566016/28242679-64bbc8e4-69b2-11e7-9f62-6a0691c37481.png)

**Comment by tonydspaniard** [comment]
done on 1.0.8 

thank you very much for your feedback
