### ISSUE TITLE
Migraion failed: Invalid path alias: @Da\\User\\Migration

### ISSUE THREAD

**Issue by tekord** [2amigos/yii2-usuario#26]
Advanced template, no any migrations applied before. 

### What steps will reproduce the problem?

yii migrate --migrationNamespaces=Da\\User\\Migration

### What is the expected result?

Applied migration.

### What do you get instead?

Yii Migration Tool (based on Yii v2.0.12)

Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @Da\\User\\Migration'

**Comment by tekord** [comment]
Oh, I got it! Your docs has escaped slash character. It works without escaping in my case. Maybe you should put note about it.

**Comment by tonydspaniard** [comment]
@tekord Great you have found the issue and thanks for pointing that out. Maybe you could help me with a PR?

**Comment by tekord** [comment]
@tonydspaniard I'd like to. Maybe on next week when I'll have some time :)

**Comment by tonydspaniard** [comment]
Thank you very much @tekord
