### ISSUE TITLE
How to login user directly after registration?

### ISSUE THREAD

**Issue by kwazaro** [2amigos/yii2-usuario#261]
### What steps will reproduce the problem?
Create new account via Registration form
### What is the expected result?
User should be logged in directly after registration and redirected to /user/settings/profile for adding additional profile information
### What do you get instead?
After registration submit it redirects to Login form

**Comment by kwazaro** [comment]
Is this code in ```@app/config/web.php``` the right approach?
```
'modules' => [
    'user' => [
        'class' => Da\User\Module::class,
        'controllerMap' => [
            'registration' => [
                'class' => Da\User\Controller\RegistrationController::class,
                'on ' . Da\User\Event\FormEvent::EVENT_AFTER_REGISTER => function ($event) {
                    $user = \Da\User\Model\User::findOne([
                        'username' => $event->getForm()->username, 
                        'email'=>$event->getForm()->email,
                    ]);
                    if ($user) {
                        \Yii::$app->user->switchIdentity($user);
                    }
                    \Yii::$app->response->redirect(['/user/settings/profile']);
                },
            ],
        ],
    ],
],
```

**Comment by tonydspaniard** [comment]
Yes @kwazaro that is cool to do. Nevertheless, by default registration sends a welcome mail to the user that needs to confirm its email (upon configuration). Make sure the email is confirmed (or do not require that by configuration).
