### ISSUE TITLE
Error Auth Tf Enabled must be an integer

### ISSUE THREAD

**Issue by Sirgalas** [2amigos/yii2-usuario#262]
### What steps will reproduce the problem?
readct user by url  user/admin/update?id=
### What is the expected result?
editing performed
### What do you get instead?
 'auth_tf_enabled' => [ 'Auth Tf Enabled must be an integer.', ],
The error is caused by the fact that the boolean field type returns the following values in the PostgreSQL database 

> TRUE
> 't'
> 'true'
> 'y'
> 'yes'
> 'on'
> '1'
> For the "false" state, the following values can be used:
> FALSE
> 'f'
> 'false'
> 'n'
> 'no'
> 'off'
> '0'

what you can see[ here.]( https://www.postgresql.org/docs/9.1/static/datatype-boolean.html)
You have validation in User model 
`"twoFactorEnabledNumber' = > ['auth_tf_enabled', 'integer'] `while this migration m000000_000006_add_two_factor_fields overrides the boolean field type

**Comment by d4rkstar** [comment]
Hello, same problem here.

Using a work around at this moment. Override the User model as described in [Documentation](https://yii2-usuario.readthedocs.io/en/latest/enhancing-and-overriding/overriding-classes/):

```
namespace app\models;

class User extends \Da\User\Model\User
{
    public function beforeValidate()
    {
        $this->auth_tf_enabled = ($this->auth_tf_enabled === true) ? 1 : 0;
        return parent::beforeValidate();
    }

    public function beforeSave($insert)
    {
        $this->auth_tf_enabled = ($this->auth_tf_enabled === 1);
        return parent::beforeSave($insert);
    }
}
```

But in my opinion this should be solved by changing the validation rule in the basic model as identified by @Sirgalas

**Comment by tonydspaniard** [comment]
re #322

**Comment by Sirgalas** [comment]
You can ask why the question was closed if you have not changed a line of code and the error remained ? Composer I updated

**Comment by tonydspaniard** [comment]
@sirgalas check #322 is fixed but on master, not yet version deployed
