### ISSUE TITLE
Override RegistrationController ends in an error Getting unknown property: yii\web\Application::enableRegistration

### ISSUE THREAD

**Issue by Stefan39** [2amigos/yii2-usuario#27]
### What steps will reproduce the problem?
I have override the RegistrationController like the docs describe.

### What is the expected result?
Do the controller-job and shows the view

### What do you get instead?
The follow error:

Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: yii\web\Application::enableRegistration

**Comment by Stefan39** [comment]
Sorry, i have use the wrong url. With /user/registration/register this works.

**Comment by tonydspaniard** [comment]
@Stefan39 glad you found the issue 👍
