### ISSUE TITLE
About mailer config: read from params 

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#271]
### What steps will reproduce the problem?
w/o any modules we have this sender.
https://github.com/arogachev/yii2-app-advanced/blob/80e3116361224e82b3cb68b08ce57de900c22cf9/frontend/models/PasswordResetRequestForm.php#L63
This is params from params config.
https://github.com/arogachev/yii2-app-advanced/blob/80e3116361224e82b3cb68b08ce57de900c22cf9/common/config/params.php#L4

### What is the expected result?
Of course I will expect same behavior for module.
### What do you get instead?
I must configure additional property in module independence of other mail settings for my project.
https://github.com/2amigos/yii2-usuario/blob/master/docs/installation/mailer.md
 This is terrible. Additional I can't see support of closure for this property...

**Comment by tonydspaniard** [comment]
The mail parameter `fromEmail` was different because we tend to change the email used everywhere according to the service used on the system (no-reply, admin, support, etc). 

I know is not the best... but setting one property again I don't think is that terrible 😄

**Comment by maxxer** [comment]
I think this can be closed, implemented in #274
