### ISSUE TITLE
user/admin/assignments?id=1 trigger unhandled error in some case

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#273]
`user/admin/assignments?id=1` has trigger a non-handled error
### What steps will reproduce the problem?
login as `admin` role
go `user/admin/assignments?id=1`
delete current webuser from console 
add user from console with `admin` role
refresh page. Login as new `admin` user
got a error.

### What is the expected result?
Refresh session?
Bad Request (#400) 
like `user/admin/assignments`?

### What do you get instead?
Invalid Configuration – yii\base\InvalidConfigException
Da\User\Widget\AssignmentsWidget::$userId is required
1. in /var/www/html/vendor/2amigos/yii2-usuario/src/User/Widget/AssignmentsWidget.php at line 46
```
   /**
     * {@inheritdoc}
     *
     * @throws InvalidConfigException
     */
    public function init()
    {
        parent::init();
        if ($this->userId === null) {
            throw new InvalidConfigException(__CLASS__ . '::$userId is required');
        }
    }
```
 in /var/www/html/vendor/2amigos/yii2-usuario/src/User/resources/views/admin/_assignments.php at line 31 – yii\base\Widget::widget(['userId' => null, 'params' => [], 'class' => 'Da\User\Widget\AssignmentsWidget'])

**Comment by maxxer** [comment]
Possibly related to #126?

**Comment by bscheshirwork** [comment]
I think "not". I can't create correctly easely trigger for differences type of key for user integer id and char on permission table. So.. I use behavior instead:
```php
    'modules' => [
        'user' => [
            'class' => Da\User\Module::class,
            'classMap' => [
                'User' => [
                    'class' => \Da\User\Model\User::class,
                    'on ' . ActiveRecord::EVENT_AFTER_INSERT => function ($event) {
                        $auth = Yii::$app->authManager;
                        $userRole = $auth->getRole('user');
                        $auth->assign($userRole, $event->sender->getId());
                    },
                    'on ' . ActiveRecord::EVENT_BEFORE_DELETE => function ($event) {
                        $id = $event->sender->getId();
                        $auth = Yii::$app->authManager;

                        return $auth->revokeAll($id);
                    },
                ],
            ],
        ],
    ],
```

All permission is revoked. I think session of user non destroyed... May be we need refresh session/ force logout user...

**Comment by bscheshirwork** [comment]
So... I remove all user session before delete user. All is ok (Problem is resolved):
```php
            'classMap' => [
                'User' => [
                    'class' => \Da\User\Model\User::class,
                    'on ' . \yii\db\ActiveRecord::EVENT_AFTER_INSERT => function ($event) {
                        $auth = Yii::$app->authManager;
                        $userRole = $auth->getRole('user');
                        $auth->assign($userRole, $event->sender->getId());
                    },
                    'on ' . \yii\db\ActiveRecord::EVENT_BEFORE_DELETE => function ($event) {
                        $id = $event->sender->getId();
                        $auth = Yii::$app->authManager;
                        \Yii::$app->session->destroyUserSessions($id);

                        return $auth->revokeAll($id);
                    },
                ],
            ],
```
Note: work with https://github.com/bscheshirwork/yii2-redis-session

**Comment by tonydspaniard** [comment]
Should we close it or write docs about it? Your call

**Comment by bscheshirwork** [comment]
I think we must close this issue without any more docs. Case is so special. This issue text can be finded if needed.
