### ISSUE TITLE
Translation missing /user/rule/create and /user/permission/create

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#276]
### What steps will reproduce the problem?
`/user/rule/create`
all labels
`/user/permission/create`
placeholder for field 'Rule'
### What is the expected result?
i18n
### What do you get instead?
en

**Comment by tonydspaniard** [comment]
Not sure I understand, mind providing an image? Thanks!

**Comment by bscheshirwork** [comment]
![peek 2018-10-22 18-33](https://user-images.githubusercontent.com/5769211/47302036-1cccff00-d629-11e8-8e55-3fdbb23a384b.gif)

**Comment by maxxer** [comment]
It's probably because `attributeLabels` method is missing in `src/User/Model/Rule.php`. But it exist in `src/User/Model/AbstractAuthItem.php`

**Comment by maxxer** [comment]
About the second `Yii::t` call is missing in `src/User/resources/views/permission/_form.php`

**Comment by bscheshirwork** [comment]
> It's probably because attributeLabels method is missing in src/User/Model/Rule.php. But it exist in src/User/Model/AbstractAuthItem.php

So... We can update src/User/Model/Rule.php like this issue top message. Do it?

**Comment by maxxer** [comment]
I'm doing it
