### ISSUE TITLE
Column not found: 1054 Unknown column 'status' in 'where clause'

### ISSUE THREAD

**Issue by rlfolden** [2amigos/yii2-usuario#28]
I used the instructions at http://yii2-usuario.readthedocs.io/en/latest/ and http://yii2-usuario.readthedocs.io/en/latest/installation/advanced-application-template/ using the standard yii2 advanced template.  I created a database, deleted m130524_201442_init.php and entered the migrations manually from a command line.  I then  configured the extension and then entered the following URL in my browser:  http://localhost/myproject/backend/web/index.php 

I expected to see a login or a redirect.

Instead, I got a Database Exception – yii\db\Exception .

**Comment by tonydspaniard** [comment]
Hi @rlfolden it seems you haven't configured the module properly as it still uses the model from the template you have downloaded: https://github.com/yiisoft/yii2-app-advanced/blob/master/common/models/User.php#L19

**Comment by rlfolden** [comment]
Thank you!
-Rudy

**Comment by tonydspaniard** [comment]
@rlfolden please, let me know if the above fixes your problem. Thanks for trying the module!

**Comment by nakarin4350** [comment]
In my backend/config/main.php 
`'bootstrap' => ['log','user'],
    'modules' => [
        'user' => [
            'class' => Da\User\Module::class,
        ]
    ], `
I still got this error "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'
The SQL being executed was: SELECT * FROM `user` WHERE (`id`=1) AND (`status`=10)".

**Comment by tonydspaniard** [comment]
@nakarin4350 whats the web `user` configuration you have? Make sure is not set to your user model.

**Comment by nakarin4350** [comment]
Thank you.It works now.
