### ISSUE TITLE
Allow to define controllerNamespace

### ISSUE THREAD

**Issue by kryvel** [2amigos/yii2-usuario#282]
Hi there!
Could you please add possibility  to define controllers namespace?
Currently it is hardcoded in Bootstrap.php

```
protected function initControllerNamespace(WebApplication $app)
    {
        $app->getModule('user')->controllerNamespace = 'Da\User\Controller';
        $app->getModule('user')->setViewPath('@Da/User/resources/views');
    }
```
and it isn't possible to define own namespace.

I know that there is controllerMap, but it's more convenient to define namespace only once, than do it for each of controllers.

### What steps will reproduce the problem?
Try to define controllerNamespace as following
```
'user' => [
    ...
    'controllerNamespace' => 'custom\controllers',
    ...
]
```
### What is the expected result?
`Yii::getModule('user')->controllerNamespace === 'custom\controllers'`

### What do you get instead?
`Yii::getModule('user')->controllerNamespace === 'Da\User\Controller'`

Thanks in advance

**Comment by tonydspaniard** [comment]
@kryvel any pull requests welcome. Currently collaborators and my self are quite busy, help is highly appreciated.

**Comment by kryvel** [comment]
I can prepare PR. Maybe you have an idea how to fix it in the best way ?

Also I'm working on preparing REST full user management interface based on your module, so after I'll finish it, I'll create PR too. Maybe somebody will find it usefull.

**Comment by tonydspaniard** [comment]
> Also I'm working on preparing REST full user management interface based on your module, so after I'll finish it, I'll create PR too. Maybe somebody will find it usefull. 

I bet they will 👍 

Maybe a property set but I am not sure. @maxxer could bring some light here too.

**Comment by maxxer** [comment]
Can you give a try to the linked PR? It should do what you want.

Out of curiosity, why you need to change that?
