### ISSUE TITLE
API application name 'api' prepended to URL created via the api

### ISSUE THREAD

**Issue by dbd5** [2amigos/yii2-usuario#288]
### What steps will reproduce the problem?
Calling functions makeConfirmationMailerService and ResendConfirmationService::class from my api endpoint creates a confirmation email link that begins with 'api' as in the following example;

Please click the link below to complete your pas=sword reset;
**https://api.domain.com/user/confirm/11/irT3i3Ov=Y7kS7LJpzSOxNGEjex7ISN2T**

### What is the expected result?
It should not start with 'api' as below;
**https://domain.com/user/confirm/11/irT3i3Ov=Y7kS7LJpzSOxNGEjex7ISN2T**

### What do you get instead?
Reset links created via API call are preceded with 'api' (Application name)

Please advise how to resolve, thanks

**Comment by maxxer** [comment]
Urls are created in [Token.php](src/User/Model/Token.php:99), and are of course generated with the current domain. 

If you need to generate urls using a different TLD I think the only option is to add a config param with the frontend hostname...

**Comment by maxxer** [comment]
I mean you should add a config param for your api with the url to be used. then in the above `Token.php`, when the url is generated, you prepend the host... Or, better, you could tell Yii2 that the host to be used is the one from config. Please do some searches, otherwise come back we'll see how to do it

**Comment by Wautvda** [comment]
I do have the same problem when sending the "Send password recovery" email from the admin console. It's send through the admin part, but regular users cannot acces that (website/admin/user/....) instead of (website/user/...).
Haven't found a way around this (yet).

**Comment by tonydspaniard** [comment]
@Wautvda & @dbd5 The way to do it is by overriding the `Token` model. (https://yii2-usuario.readthedocs.io/en/latest/enhancing-and-overriding/overriding-classes/). When you do, you need to override the method `Token::getUrl()`, it forces the scheme.

I would get the URL without forcing the host info to be prefixed (`$scheme=false`) and then use the frontend url from the Yii params (according to the environment).
