### ISSUE TITLE
deploy app ubuntu no work

### ISSUE THREAD

**Issue by rodriguez90** [2amigos/yii2-usuario#292]
hello guys.
I' am use  this package and deploy my web app in ubuntu 16.04 and this no work

![image](https://user-images.githubusercontent.com/15237850/48862606-dcca7a80-ed94-11e8-9dee-e83114d5c0f5.png)
![image](https://user-images.githubusercontent.com/15237850/48863181-79414c80-ed96-11e8-8d32-a7fbf3cf7288.png)
![image](https://user-images.githubusercontent.com/15237850/48863195-82cab480-ed96-11e8-8dea-88af56311e6f.png)

**Comment by maxxer** [comment]
More likely you haven't correctly set up url rewriting in your apache config
