### ISSUE TITLE
2fa missing form

### ISSUE THREAD

**Issue by gomonkey** [2amigos/yii2-usuario#296]
Sorry but after scanning QR code is not possible to able it because is missing form 

https://github.com/2amigos/yii2-usuario/blob/master/src/User/resources/views/settings/two-factor.php

**Comment by gomonkey** [comment]
My mistake, it is rendering by ajax

**Comment by TimoB2005** [comment]
@gabriele-carbonai my form is not rendering too on all 2fa methods, what was your fix???
Take a look: https://github.com/2amigos/yii2-usuario/issues/529
