### ISSUE TITLE
Adaption to Yii 3.x planned?

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-usuario#298]
Are you planning to update this module to Yii 3.x? I know it's pre-alpha yet, but this is more a general question...

**Comment by maxxer** [comment]
Of course we want to keep the extension up to date. 

Most of the devs are currently busy, but we'll certainly make usuario yii3 compatible

**Comment by tonydspaniard** [comment]
I am coming back this week :)

**Comment by philippfrenzel** [comment]
any update on this? ;)

**Comment by Thoulah** [comment]
I would say bootstrap4 first, as that is actually released already

**Comment by tonydspaniard** [comment]
@schmunk42 @Thoulah @philippfrenzel What do you think about the following, split the module into the following packages: 

* `2amigos/yii3-usuario` -> core library
* `2amigos/yii3-usuario-b4-views` -> sample bootstrap views (other packages may be created -i.e. material-views, tailwind-views, etc)
* `2amigos/yii3-usuario-gpdr` -> package to provide gdpr mechanism
* `2amigos/yii3-usuario-2fa` -> package to provide two factor mechanism

I think keeping this library structure it will become hard to maintain. So I am thinking to split its code. What do you guys think? Any ideas welcome.

**Comment by Thoulah** [comment]
I think that's the same way Yii3 is going. Although putting views outside of main package might be a bit weird (if I understand correctly).
In my own project I created a few classes inside bootstrap4 (sub)namespace. In case bootstrap5 differs I can just add classes into a new bootstrap5 namespace and support both.

**Comment by schmunk42** [comment]
I'd recommend to prefix them with `yii-`, see https://github.com/yiisoft/docs/blob/master/000-packages.md - since we've switched to semantic versioning.

**Comment by tonydspaniard** [comment]
@Thoulah the reason why views are outside is because I am planning to create a core version that could be used via api or desktop (web controllers). So, there would be an API package and a WEB package that will include controllers and a reference to the view they would like to use. Thats the idea.

**Comment by Thoulah** [comment]
Now it makes sense :+1:

**Comment by tonydspaniard** [comment]
I have been talking to Alex Makarov and he told me that migrating to Yii3 still too early. Maybe we should wait a little.

**Comment by tonydspaniard** [comment]
re #323
