### ISSUE TITLE
fail2ban support

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#306]
As an enhancement it can be useful to support fail2ban. It's basically to log somewhere failed logins with source IP, so they can be parsed by fail2ban and blocked if abused.

**Comment by ivan-cc** [comment]
You can use your own log files and [Form Events](https://github.com/2amigos/yii2-usuario/blob/master/docs/events/form-events.md) (FormEvent::EVENT_AFTER_LOGIN).

**Comment by maxxer** [comment]
Unfortunately that event [is fired](src/User/Controller/SecurityController.php#L148) only after a **successful** login

**Comment by ivan-cc** [comment]
Then you can use two events (`EVENT_BEFORE_LOGIN `& `EVENT_AFTER_LOGIN`). Or override the class `SecurityController`.

**Comment by tonydspaniard** [comment]
@maxxer isn't this more a server configuration stuff? On another note, how hard would it be to create a Filter that would act as Fail2ban without forcing the user to go throughout much hassle? 

- Check number of failed attempts 
- Provide wait mechanism for those over 3 failed attempts (message could remind them to go throughout the password recovery mechanism) 
- Ban after X number of times (i.e. configurable max number of attempts prior to ban) and force user to only be able to login via recovery

**Comment by maxxer** [comment]
Indeed there are other means for blocking such attempts (like Yii2 rate limiter, somehow). The value of fail2ban is that it blocks the requests at server level with iptables, so they won't even reach the webserver and require php work. 

For f2b to work there must be a log file to be monitored and parsed, that was my initial request.

**Comment by tonydspaniard** [comment]
Is the access.log? I think is worth adding it.
