### ISSUE TITLE
create a release

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-usuario#308]
### What steps will reproduce the problem?

Upgrade to PHP 7.3, run into regex bug fixed in https://github.com/2amigos/yii2-usuario/commit/4084c555924f94cb1578dfffb59c3fa9f6fd9293

Try to update to a beta or rc version.

### What is the expected result?

A beta or rc version with the fix available.

### What do you get instead?

Need to update to `dev-master#a771f287b2893ccd4677ea4ffd6c904bc3675b0a`

**Comment by maxxer** [comment]
I'll do this long expected release in the next days, unless @tonydspaniard is up before me ;)

**Comment by maxxer** [comment]
1.5.0 has been (finally) tagged
