### ISSUE TITLE
Extending RegistrationForm requires extending User

### ISSUE THREAD

**Issue by mattheobjornson** [2amigos/yii2-usuario#31]
Hi,
I've had a requirement to add captcha to the RegistrationForm and noticed that [RegistrationController](https://github.com/2amigos/yii2-usuario/blob/master/src/User/Controller/RegistrationController.php#L104) passes all form attributes to the User Model. So I needed to extend also User model with the same (dummy) captcha attribute. Is it possible to avoid this overhead and for example ignore attributes that are present in the RegistrationForm when they do not exist in the User model?
Thank you.

**Comment by tonydspaniard** [comment]
No need to extends User too. What we normally do is simply override the RegistrationController's register method with your own. And configure the module's controllerMap like this: 

On your config
```php 
'controllerMap' => [
        'registration' => [
            'class' => '\app\controllers\RegistrationController',
        ],
    ]
```

On your controller: 

```php 

class RegistrationController extends \Da\User\Controller\RegistrationController 
{
        public function actionRegister()... 

```

Sorry if there is any bug, is just to expose the idea. I have just realized the docs is not right but here is a tuto (missing the controllerMap part) http://yii2-usuario.readthedocs.io/en/latest/helpful-guides/how-to-add-captcha-widget/

**Comment by tonydspaniard** [comment]
done: https://github.com/2amigos/yii2-usuario/blob/master/docs/helpful-guides/how-to-add-captcha-widget.md#configure-module-and-application

**Comment by mattheobjornson** [comment]
Thanks for the feedback. Yes, generally it works fine, my concern is just RegistrationForm, because when I add attribute there
```php
class RegistrationForm extends \Da\User\Form\RegistrationForm
{
    public $verifyCode;
...
}
```
RegistrationController, when form is submitted, fills the User object with all attributes of RegistrationForm
```php
...
    /** @var User $user */
    $user = $this->make(User::class, [], $form->attributes);
...
```
and it fails on `Setting unknown property: Da\User\Model\User::verifyCode`
so I have to extend also User model with
```php
class User extends \Da\User\Model\User
{
    public $verifyCode;
...
}
```
And this last steps seems to me redundant. But it is also possible that I am missing something here...

**Comment by tonydspaniard** [comment]
@mattheobjornson that is why you can create your own controller that will do the following: 

```php 
if($form->validate()) { //<--- verify code checked here!
// ... other logic
/**@var \Da\User\Model\User $user */
$user = $this->make(User::class, [], $form->getAttributes(['username', ... all attributes BUT verifyCode ...])

```

**Comment by mattheobjornson** [comment]
OK, thanks, I will do it one way or another. I've only got distracted by this during migration from dektrium/yii2-user where for this particular case I didn't need to handle anything outside the RegistrationForm :)

**Comment by tonydspaniard** [comment]
@mattheobjornson yes that is true. Is a great extension, and I thank you for giving a try ours. We tend to work with DI as much as possible and once you get a grasp around it, I am sure you will see its full potential. Sometimes, makes sense a bit of extra effort to keep your code as clean as possible. 

Best regards and thanks for the conversation and feedback

**Comment by Thoulah** [comment]
I have created the dummy `User` model, as it is the quickest way. Should be made unneeded imho. Otherwise put it in the guide :)

Also
```
                        'enableAjaxValidation' => true,
                        'enableClientValidation' => false,
```
I had to reverse as above does not work:

```
                        'enableAjaxValidation' => false,
                        'enableClientValidation' => true,
```
