### ISSUE TITLE
gravatar image don't work

### ISSUE THREAD

**Issue by paskuale75** [2amigos/yii2-usuario#311]
### What steps will reproduce the problem?
I registered with an email connected to Gravatar.com
### What is the expected result?
my gravatar should appear
### What do you get instead?
shows me the G on a blue background

**Comment by paskuale75** [comment]
Must add email twice in user->profile for see gravatar in function, sorry it work like a charm! ;)

**Comment by tonydspaniard** [comment]
Good to know you found the solution @paskuale75
