### ISSUE TITLE
Migration m000000_000006_add_two_factor_fields in postgres DB 

### ISSUE THREAD

**Issue by Sirgalas** [2amigos/yii2-usuario#313]
### What steps will reproduce the problem?
An error occurred while performing the migration 
Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "at_tf_enabled" is of type boolean bit default expression is of type integer
HINT: You will need to rewrite or cast the expression.
The SQL being executed as: ALTER TABLE "user" ADD "auth_tf_enabled" boolean DEFAULT 0

### What do you get instead?
Fixed in vendor line 21
$$this->add Column('{{%user}}', 'auth_tf_enabled', $this->boolean()->defaultValue(0));
upon
$$this->add Column('{{%user}}', 'auth_tf_enabled', $this->boolean()->defaultValue(false));
migration is applied

**Comment by maxxer** [comment]
what database & version are you using?

**Comment by tonydspaniard** [comment]
This seems the same issue as #211

**Comment by demonking** [comment]
@Sirgalas download the new version and try it again, but this ticket is also around 2 month's old.
Maybe close, when there is still an error reopen it? :)

**Comment by tonydspaniard** [comment]
You are correct @demonking

**Comment by tinythick** [comment]
This bug still exisits. A fix was committed in v1.5-beta but not included in v1.5 release
