### ISSUE TITLE
Allow sqlite database in migrations

### ISSUE THREAD

**Issue by santilin** [2amigos/yii2-usuario#315]
Currently, sqlite is not supported in the migrations due to src/User/Helper/MigrationHelper.php checking the driver name in the `resolveTableOptions` and `resolveDbType` functions.

I have used the `santilin/yii2-sqlite3-full-support` extension in my project and all the `yii2-usuarios` migrations are supported, so it would be nice to allow yii2-usuario to use sqlite and perhaps add to the docs that the `yii2-sqlite3-full-support` can be used.

**Comment by maxxer** [comment]
You mean by just installing the extension sqlite works out of the box? 

If you want to prepare a pull request it would be welcome ;)

**Comment by santilin** [comment]
Installing the extension and changing the controllerMap for sqlite\QueryBuilder in the application entry path.

I'll prepare that PR

**Comment by tonydspaniard** [comment]
New package should be optional... In Dev. Thoughts?

**Comment by maxxer** [comment]
I'd just document how to do it, not include into the main code

**Comment by tonydspaniard** [comment]
@santilin do you mind providing the documentation reference on the docs. I agree with @maxxer

**Comment by santilin** [comment]
I have updated my extension so that there is no need to set up anything. It uses now the Yii2 extension loading feature to set up the classMap. 

I'll do the PR ASAP.

**Comment by tonydspaniard** [comment]
Thank you @santilin

**Comment by santilin** [comment]
I'm having trouble trying to run the tests.
1) The file `tests/_app/config/db.php` is not read. Instead, the config set in `codeception.dist.yml` is read (the docs states that I should use the former one)
2) Even though I have set up a mysql database, there is a  `SET NAMES=utf8` in de Codecpetion `Db` module so the tests fail.

**Comment by tonydspaniard** [comment]
@santilin we can fix the tests after you make the PR request.

**Comment by tonydspaniard** [comment]
@santilin even though the PR was closed, the changes to the code were made and work credits given to you. 

Thanks for the PR.

**Comment by santilin** [comment]
Thanks!
