### ISSUE TITLE
How to ovveride Profile

### ISSUE THREAD

**Issue by giannisdag** [2amigos/yii2-usuario#319]
### What steps will reproduce the problem?
Follow the instructions to override the Profile class, 
https://yii2-usuario.readthedocs.io/en/latest/enhancing-and-overriding/overriding-classes/
### What is the expected result?
When I call the action `user/settings/profile`, I should see a form for filling the profile data
### What do you get instead?
Error, Argument 1 passed to Da\User\Event\ProfileEvent::__construct() must be an instance of Da\User\Model\Profile, instance of app\models\Applicant given
ProfileEvent is directly associated with Da\User\Model\Profile

**Comment by tonydspaniard** [comment]
Can you show the code of your `Profile` model? And also the one that you use to configure your events?

**Comment by giannisdag** [comment]
Hi Tony, I have checked this one more time, the problem is I did not inherited the new Profile model from the basic
`use Da\User\Model\Profile as BaseProfile;` 
The only problem with this approach is that I have to use data fields that are not needed in this specific project, and it would be better if someone could implement a basic interface profile by setting it's own attributes for the model instead of inheriting the model (just a thought). Anyway, thanks for this awesome extension!!!

**Comment by tonydspaniard** [comment]
I think you are correct. I'll take that into account on our next version.
