### ISSUE TITLE
Linkedin login dosn't work

### ISSUE THREAD

**Issue by upsellpl** [2amigos/yii2-usuario#321]
### What steps will reproduce the problem?

Enabled social login and LinkedIn API configured.

### What is the expected result?

Log in to the app using the Linkedin account.

### What do you get instead?

No new user account created and the user is not logged in.

I think instead of:
$this->getUserAttributes()['email-address']
should be:
$this->getUserAttributes()['email']
in Linkedin connector.

**Comment by maxxer** [comment]
Indeed it seems a legit change. Did you verify the new field? thanks

**Comment by upsellpl** [comment]
@maxxer it works with 'email'.

**Comment by tonydspaniard** [comment]
@upsellpl mind dropping the response here. Thanks.

**Comment by tonydspaniard** [comment]
done, fix added to support both responses
