### ISSUE TITLE
Key "username" is not a column name and can not be used as a filter

### ISSUE THREAD

**Issue by TmorezT** [2amigos/yii2-usuario#337]
I'm trying to login in a portal and this errors occurs. Kindly help me.

![Invalid Argument – yii_base_InvalidArgumentException - localhost](https://user-images.githubusercontent.com/53572706/62303113-3aff3f80-b484-11e9-8b37-2ee9c639d315.png)

**Comment by tonydspaniard** [comment]
What is the User model you use?

**Comment by demonking** [comment]
Maybe close here, 24 day's without response

**Comment by dhaneshwarsingh** [comment]
Hi 
I am getting the same error what should I do?

**Comment by maxxer** [comment]
Can you post the full stack trace? Did you customize any model?
