### ISSUE TITLE
Unable to override i18n translation config

### ISSUE THREAD

**Issue by tekord** [2amigos/yii2-usuario#34]
Usuario module's bootstrap method called earlier than any custom boostrap components if you open user/login page. This makes impossible to override translation which initialized in \Da\User\Bootstrap::initTranslations.

### What steps will reproduce the problem?

Create StartUp class:

```php
class AdHocStartUp implements BootstrapInterface {
	/**
	 * @inheritDoc
	 */
	public function bootstrap($app) {
		$app->i18n->translations['usuario*'] = [
			'class' => PhpMessageSource::class,
			'basePath' => '@common/messages', // here is copy of usuario.php dictionary with translated messages
			'sourceLanguage' => 'en-US',
		];
	}
}
```

### What is the expected result?

Translated messages from `@common\messages`.

### What do you get instead?

Messages from modules' path + '/resources/i18n'

Any idea how to fix this?

**Comment by tonydspaniard** [comment]
What messages would you like to replace?

**Comment by tekord** [comment]
At that moment my pull request was pending, so I wanted to override base path for usuario's i18n to use russian translations in my application. I made a fix which also is a feature (PR).

**Comment by tonydspaniard** [comment]
@tekord Why not updating the russian translations here? I would happily add your translations to the module.

**Comment by tekord** [comment]
@tonydspaniard hi! This issue is not relevant to me now but I want you to focus on that line: https://github.com/2amigos/yii2-usuario/blob/9ce1c1b5021b8317410527edba6c406ee55d30ae/src/User/Bootstrap.php#L167

You checking if `translations['usuario*']` is set in i18n, but it cannot be set ever because usario's Bootstrap runs BEFORE any application bootstrap. Usario's Bootstrap is added to vendor/yiisoft/extensions.php, so there is no way to set this translation before this Bootstrap call except the case when I created my own extension and composer is register my bootstrap BEFORE usario's bootstrap.

I think that isset check was intention to make it customizable, but it is failed. The solution was in my PR https://github.com/2amigos/yii2-usuario/pull/35

What do you think?
