### ISSUE TITLE
Advice: How to implement sign in / log in form in modal ?

### ISSUE THREAD

**Issue by khvalov** [2amigos/yii2-usuario#343]
Is any easy way how it's possible to implement sign-in / sign up form to get open into modal via ajax?

**Comment by demonking** [comment]
@khvalov it's not that easy to explain it whole steps in this issue.
I would suggest you this guide https://www.yiiframework.com/wiki/806/render-form-in-popup-via-ajax-create-and-update-with-ajax-validation-also-load-any-page-via-ajax-yii-2-0-2-3

**Comment by khvalov** [comment]
@demonking thanks. Expected kind of easy approach, but seems there is no such. The general approach is clear enought for me (have sufficient experience to deal with Yii2+modal+a(p)jax)

**Comment by demonking** [comment]
@khvalov your welcome. If there isn't any question, maybe you could close the issue? :)
