### ISSUE TITLE
ReCaptcha field not being validated.

### ISSUE THREAD

**Issue by BillHeaton** [2amigos/yii2-usuario#345]
### What steps will reproduce the problem?
Follow the steps in yii2-usuario/docs/helpful-guides/how-to-use-recaptcha-widget.md 

### What is the expected result?
Validated ReCaptcha. (i.e. not checking the box should generate an error.)

### What do you get instead?
ReCaptcha is displayed however it is not send to google for validation.  You can leave it unchecked and the password reset is still delivered.

### Solution ###
RecoveryForm uses scenarios for processing.  However the default only has 'email'

Follow the instructions from the help guide for adding $captcha and rules to the RecoveryForm override. After the rules() add scenarios():
```
    public function scenarios()
    {
        return [
            self::SCENARIO_REQUEST => ['email', 'captcha'],
            self::SCENARIO_RESET => ['password'],
        ];
    }

```

**Comment by demonking** [comment]
Could you provide more Code?

**Comment by BillHeaton** [comment]
See "Solution"

**Comment by BillHeaton** [comment]
Code is in #347
