### ISSUE TITLE
Missing redirection on rule delete action.

### ISSUE THREAD

**Issue by Eseperio** [2amigos/yii2-usuario#357]
### What steps will reproduce the problem?
Delete a rule.
### What is the expected result?
Redirection to rules action.
### What do you get instead?
White screen.

**Comment by demonking** [comment]
It happens everytime?

If not, could you provide a logfile?

**Comment by Eseperio** [comment]
Function is missing return statement.
https://github.com/2amigos/yii2-usuario/blob/4208e0c38a3775fae728dde7b500d4ffbf62239d/src/User/Controller/RuleController.php#L130
