### ISSUE TITLE
Google social login

### ISSUE THREAD

**Issue by drSun** [2amigos/yii2-usuario#362]
Hi, we've got for a google this code:
`
public function getEmail()
    {
        return isset($this->getUserAttributes()['emails'][0]['value'])
            ? $this->getUserAttributes()['emails'][0]['value']
            : null;
    }
`

But google doesn't return any columns like `['emails'][0]['value']` in my case, just simple array `['email' => '**@***']`. So I had to extend this client and make following changes:

`
public function getEmail()
    {
        return isset($this->getUserAttributes()['email'])
            ? $this->getUserAttributes()['email']
            : null;
    }
`

Then all began to work as expected.

**Comment by maxxer** [comment]
Does the current code throws an error or just returns null email?

**Comment by maxxer** [comment]
I'm asking because the `getEmail` method already implements search in both ways, on the flat array and on the multiple one. So it should be able to return both cases.

Maybe we can change it to 

```php
return ArrayHelper::getValue($this->getUserAtribues(), "emails.0.value") ?? ArrayHelper::getValue($this->getUserAtribues(), "emails");
```

Can you give it a try? I'm having troubles in setting up G auth

**Comment by drSun** [comment]
@maxxer  I'm very sorry, forgot to look at my code version. For some reason composer doesn't update usuario to the latest version, so I have an outdated code. I wonder why, because I have "2amigos/yii2-usuario": "*" in composer.json, but anyway it's my trouble. Please, close this issue.

**Comment by maxxer** [comment]
Thanks for the feedback.

As reporter you can close issues yourself. :)
