### ISSUE TITLE
Error when reinstall app: Invalid path alias: @Da/User/Migration

### ISSUE THREAD

**Issue by macklus** [2amigos/yii2-usuario#366]
### What steps will reproduce the problem?

1. Install basic app
2. composer require 2amigos/yii2-usuario:~1.0
3. configure console.php (see below)
4. run migrations
5. remove vendor directory (or just try to install on other server)
6. composer install --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --no-suggest --optimize-autoloader
7. When try to run migration again, it hangs: Invalid path alias: @Da/User/Migration

### What is the expected result?
Run migrations witouth mistakes

### What do you get instead?

Only way to solve is:
- composer remove 2amigos/yii2-usuario
- composer require 2amigos/yii2-usuario:~1.0

Seems that something that was executed on composer require was not executed when composer install, but can figure what is

**Comment by maxxer** [comment]
I don't see any config option in `composer.json` that could do something different. Also, I don't see any path alias set in the code, so I wonder how it could work in the beginning. Unless you meant namespace instead of path alias

**Comment by Thoulah** [comment]
You are running install with a bunch of options. Prehaps you could eliminate if there's an issue there. I'm suspecting the one below.

`--optimize-autoloader (-o): Convert PSR-0/4 autoloading to classmap to get a faster autoloader.`

**Comment by macklus** [comment]
Seems to be related with --optimize-autoloader
Close due to more invest are required
