### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by effsoft** [2amigos/yii2-usuario#369]
namespace Da\User\Factory\MailFactory
line 89
return static::makeMailerService(MailEvent::TYPE_CONFIRM, $from, $to, $subject, 'recovery', $params);
=>
return static::makeMailerService(MailEvent::TYPE_CONFIRM, $from, $to, $subject, 'confirmation', $params);

**Comment by maxxer** [comment]
It's fixed in master

https://github.com/2amigos/yii2-usuario/blob/master/src/User/Factory/MailFactory.php#L89
