### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by schmunk42** [2amigos/yii2-usuario#377]
### What steps will reproduce the problem?

We would need the `LOGIN_FAILED` event.

### What is the expected result?

Upgrade normally.

### What do you get instead?

We'd need to use `dev-master`.

---

I think 1.5.1 would be fine, but 1.6.0 also.

**Comment by maxxer** [comment]
Yes, you're right :( Long overdue. I'll do this weekend, ping me daily since Monday if I didn't 😅

**Comment by maxxer** [comment]
e2b041a

**Comment by schmunk42** [comment]
Great, thank you! 

CC: @eluhr
