### ISSUE TITLE
Add module attribute 'disableLogOfIps'.

### ISSUE THREAD

**Issue by jkmssoft** [2amigos/yii2-usuario#378]
I want to be able to disable the logging of IPs.
So I would add a attribute to the Module.php:
`$disableLogOfIps = false.`
So I can set it to true and then the `last_login_ip` and `registration_ip` are set to 127.0.0.1.
Ok?

Or do you prefer another name for the attribute?

I would make a PR.

**Comment by maxxer** [comment]
I'd call it `disableIpLogging`. If enabled I would also hide the relevant columns in the views.

Go ahead with the PR, thank you! Don't forget to update changelog, messages and docs

**Comment by jkmssoft** [comment]
Hi, see my PR, please have a look at it and merge it if it is OK or tell me what I have to change.
Thank you very much.

**Comment by maxxer** [comment]
thanks for the PR!
