### ISSUE TITLE
AccessRuleFilter ignoring parent properties

### ISSUE THREAD

**Issue by Eseperio** [2amigos/yii2-usuario#380]
`AccessRuleFilter` overrides `matchRole`. Since Yii 2.0.12 there is another parameter available called `permissions`. If a user defines permissions and it is using Yii2-usuario, filter will never block or allow the request. This can lead to several security bug.

**Comment by maxxer** [comment]
Thanks for reporting! From what I can see the only difference is the check for the `admin` role. I'll see if I can shorten the overridden function without breaking too many things :D

**Comment by kartik-v** [comment]
I am facing an issue on all pages after this commit... ACCESS RULE throws FORBIDDEN for all roles except admin because of [custom roles defined which were being parsed by Da\User\Filter\AccessRuleFilter](https://github.com/2amigos/yii2-usuario/blob/master/docs/installation/rbac.md#how-to-use-accessrulefilter) - can you please cross check and revert... or let know changes - not got time to understand this change.

**Comment by kartik-v** [comment]
The deletion of the following lines via this commit has caused all pages to break - can you please check @tonydspaniard / @maxxer 

```
else {
    $roleParams = $this->roleParams instanceof Closure
        ? call_user_func($this->roleParams, $this)
        : $this->roleParams;

    if ($user->can($role, $roleParams)) {
        return true;
    }
}
```

**Comment by maxxer** [comment]
commit reverted, will test better. thanks for the feedback

**Comment by maxxer** [comment]
@kartik-v can you please provide an example? I tried this but doesn't trigger forbidden, it wor

```php
'access' => [
   'class' => AccessControl::className(),
   'ruleConfig' => [
       'class' => AccessRuleFilter::class,
   ],
   'rules' => [
       [
           'actions' => ['update'],
           'allow' => true,
           'roles' => ['modifica_propri_prodotti'],
           'roleParams' => function ($rule) {
               return [
                   'tipo' => 'prodotti',
                   'fornitore' => Articolo::findOne(Yii::$app->request->get('id'))->r_fornitore,
               ];
           },
       ],
   ],
```

**Comment by kartik-v** [comment]
It's a similar config... Only difference is I have multiple roles in the roles parameter and it throws error for all roles except admin

**Comment by kartik-v** [comment]
The issue is because of the following. Try this test below and it will fail. Note that in the example below, multiple roles are configured: `admin`, `role_1` and `another_role`. 

In your changed code you are using an in_array `admin` check  and terminating the code with a `return`... which is wrong... because the other roles are not validated for right access.

```php
'access' => [
   'class' => AccessControl::className(),
   'ruleConfig' => [
       'class' => AccessRuleFilter::class,
   ],
   'rules' => [
       [
           'actions' => ['update'],
           'allow' => true,
           'roles' => ['admin', 'modifica_propri_prodotti', 'another_role'],
           'roleParams' => function ($rule) {
               return [
                   'tipo' => 'prodotti',
                   'fornitore' => Articolo::findOne(Yii::$app->request->get('id'))->r_fornitore,
               ];
           },
       ],
   ],
```

**Comment by kartik-v** [comment]
The issue is because of the following. Try this test below and it will fail. Note that in the example below, multiple roles are configured: `admin`, `role_1` and `another_role`. 

It looks like that in your changed code you are using an in_array `admin` check versus the foreach loop which maybe wrong... because the other roles other than `admin` are not being validated for right access (the access therefore works only for `admin` and not for the other roles).

```php
'access' => [
   'class' => AccessControl::className(),
   'ruleConfig' => [
       'class' => AccessRuleFilter::class,
   ],
   'rules' => [
       [
           'actions' => ['update'],
           'allow' => true,
           'roles' => ['admin', 'modifica_propri_prodotti', 'another_role'],
           'roleParams' => function ($rule) {
               return [
                   'tipo' => 'prodotti',
                   'fornitore' => Articolo::findOne(Yii::$app->request->get('id'))->r_fornitore,
               ];
           },
       ],
   ],
```

**Comment by maxxer** [comment]
Sorry for taking too long, but today I had some time and I could figure out what's wrong in my patch, which basically is the last `return false` statement. Replacing it with the original implementation should fix my patch and fix the original reported problem.

If anyone can spare some time to make a test it would be great.
Thanks everyone

```patch
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 5176f7e..637e949 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,6 +1,7 @@
 # CHANGELOG
 
 ## work in progress
+ - Fix #380: Avoid rewriting AccessRule::matchRole (maxxer)
  - Fix #378: Add module attribute 'disableIpLogging' (jkmssoft)
 
 ## 1.5.1 April 5, 2020
diff --git a/src/User/Filter/AccessRuleFilter.php b/src/User/Filter/AccessRuleFilter.php
index 9b4a261..b32721f 100644
--- a/src/User/Filter/AccessRuleFilter.php
+++ b/src/User/Filter/AccessRuleFilter.php
@@ -48,40 +48,23 @@ class AccessRuleFilter extends AccessRule
 
     /**
      * {@inheritdoc}
-     * */
+     **/
     protected function matchRole($user)
     {
         if (empty($this->roles)) {
-            return true;
+            return parent::matchRole($user);
         }
 
-        foreach ($this->roles as $role) {
-            if ($role === '?') {
-                if ($user->getIsGuest()) {
-                    return true;
-                }
-            } elseif ($role === '@') {
-                if (!$user->getIsGuest()) {
-                    return true;
-                }
-            } elseif ($role === 'admin') {
-                /** @var User $identity */
-                $identity = $user->getIdentity();
-
-                if (!$user->getIsGuest() && $identity->getIsAdmin()) {
-                    return true;
-                }
-            } else {
-                $roleParams = $this->roleParams instanceof Closure
-                    ? call_user_func($this->roleParams, $this)
-                    : $this->roleParams;
-
-                if ($user->can($role, $roleParams)) {
-                    return true;
-                }
-            }
+        // We just check our custom role "admin" otherwise call back the original implementation
+        if (!in_array("admin", $this->roles)) {
+            return parent::matchRole($user);
+        }
+        /** @var User $identity */
+        $identity = $user->getIdentity();
+        if (!$user->getIsGuest() && $identity->getIsAdmin()) {
+            return true;
         }
 
-        return false;
+        return parent::matchRole($user);
     }
 }

```

**Comment by maxxer** [comment]
I'm pushing the patch above, report back in case of problems. thanks

**Comment by ajmedway** [comment]
Hi folks, just been rather puzzled by something... Why is the "admin" role hard-coded in here? Should it not be looking at the module config `administratorPermissionName` param?


``` 
> Also you can define access role `'administratorPermissionName' => 'admin',` where `admin` is have `administrateUser` permission
```php
...
    'modules' => [
        'user' => [
            'class' => Da\User\Module::class,
            'administratorPermissionName' => 'admin',
        ],
    ],
...
```
