### ISSUE TITLE
assign a default role to user upon user creation

### ISSUE THREAD

**Issue by whisere** [2amigos/yii2-usuario#382]
What is the best way to assign a default role to user upon user creation? is there option available in the settings to do that, or need to change module code? Thanks!

**Comment by maxxer** [comment]
Use [events](https://yii2-usuario.readthedocs.io/en/latest/events/user-events/). You can choose what's best suited for you, like after registration or after user creation, and assign the role you wish.

**Comment by whisere** [comment]
That's great! Many thanks!!
