### ISSUE TITLE
Double flash message

### ISSUE THREAD

**Issue by code4d1** [2amigos/yii2-usuario#384]
When register a new user or click link from email confirmation, etc, always give me double flash message

I've tried to use flash message outside the module and it's okay with no double displayed.

I used Yii 2.0.35 with basic template, then install yii2-usuario via composer (version installed = 1.5.1)

My Setting for the module :
`'modules' => [
        'user' => [
            'class' => Da\User\Module::class,            
            'administrators' => ['admin'], 
            'generatePasswords' => true,
        ]
    ],`

![confirmPNG](https://user-images.githubusercontent.com/4345784/85173141-1fbc3f00-b2a5-11ea-8bf2-d975a87d5627.PNG)
![register](https://user-images.githubusercontent.com/4345784/85173143-20ed6c00-b2a5-11ea-83e0-c3cefa63ec1a.PNG)

**Comment by cgsmith** [comment]
I received this as well and was looking for a solution. I recommend that the package has a separate module configured to let the application handle flash messages.

So for example, `enableFlashMessages` should be **true** which allows for the flash messages to be generated. But then `enableFlashMessageView` should be **false** to allow for someone else's code to display it. I'll have a PR soon.

**Comment by maxxer** [comment]
Sorry for taking so long.

I checked the PR and I'm not sure it's the best fix. According to the docs the `enableFlashMessages` should do the same, @code4d1 did you try setting this param to `false`? According to the config snipped you added initially that's to the default value, which is `true`

**Comment by cgsmith** [comment]
@maxxer `enableFlashMessages` set to `false` removes the flash message from being added to the array. This isn't desirable because we are just looking for a solution to remove the duplicate flash messages. We still need the usuario plugin to bubble up the flash message.

**Comment by maxxer** [comment]
As I wrote in the PR if you check all the `->setFlash` almost none of them are set considering the value of `enableFlashMessages`, that means setting that to false doesn't remove the message from the session.

**Comment by cgsmith** [comment]
@maxxer perhaps Usuario should be deleting the flash messages it posts then?

**Comment by maxxer** [comment]
This could be a good solution, but must be tested. IMHO if you display flash messages in the layout are they rendered before or after the view? In the first case you'd still get double flashes

**Comment by cgsmith** [comment]
It is rendered as a whole. I changed the PR to delete the flash messages that are displayed. This will correct the main issue reported in the bug.

**Comment by maxxer** [comment]
fix merged
