### ISSUE TITLE
Add `last_login_at` field to user table

### ISSUE THREAD

**Issue by pappfer** [2amigos/yii2-usuario#39]
I think it's a useful feature to have a `last_login_at` field in the user table. Dektrium also added this functionality to his user module this January. I'm happy to implement it and send a PR if you also think it's a good idea.

**Comment by tonydspaniard** [comment]
All yours @pappfer do not forget to add the credit on the CHANGELOG. Thank you very much for your interest

**Comment by pappfer** [comment]
I submitted a pull request, but for some reason the Travis CI build fails.

**Comment by tonydspaniard** [comment]
Thank you @pappfer for the submission, there is a small change to do. Do not worry about the tests, is an issue with assets (again). I'll try to fix that my self prior the release of a new version.

**Comment by tonydspaniard** [comment]
@pappfer I have fixed prior issues but it seems we have new one: 

https://travis-ci.org/2amigos/yii2-usuario/jobs/259425295

**Comment by pappfer** [comment]
@tonydspaniard Thank you, I'll fix that later today.
However I'm just switching from dektrium's user module to this one and I have a problem. On the login page the browser says "too many redirects". Even if I commented out the `routes` section at the module config, it still wants to redirect from `/user/security/login` to `/user/login`. Do you have any idea why?
