### ISSUE TITLE
Debugging on transport layer

### ISSUE THREAD

**Issue by WeeSee** [2amigos/yii2-usuario#392]
I cannot send emails out, e.g. when a password link should be send out. Email is not working at all.

There is just a flash message saying "Unable to send recovery message to the user".

I think that this is a transport problem. There are tons of things that can go wrong here: firewall issues, tls-/security-settings, self-signed certificates, wrong ports, hostname-typos, ...

How to debug transport layer? How to enable debugging to trace connection to the email service?

**Comment by liviuk2** [comment]
Hi,
if you use swiftmailer you can redirect log messages to a file and analyse them, in log configuration you can add an entry like:
```
        [
            'class' => 'yii\log\FileTarget',
            'logVars' => [], // system vars usually in this case are not so useful, you can avoid log them to get better readability
            'categories' => ['yii\swiftmailer\Logger::add'],
            'logFile' => '@runtime/logs/email.log',
        ],
```

I suppose also other transport layers use a specific category when logging, probably you could log also those categories if you use something different.

**Comment by GiorgiaMenozzi** [comment]
Hi, 
you can also change the mailing configuration params  with 

> 'useFileTransport' => TRUE

for documentation refer to https://www.yiiframework.com/doc/guide/2.0/en/tutorial-mailing

maybe non directly in prod environment configuration but in a test configuration

**Comment by WeeSee** [comment]
> Hi,
> if you use swiftmailer you can redirect log messages to a file and analyse them, in log configuration you can add an entry like:
> 
> ```
>         [
>             'class' => 'yii\log\FileTarget',
>             'logVars' => [], // system vars usually in this case are not so useful, you can avoid log them to get better readability
>             'categories' => ['yii\swiftmailer\Logger::add'],
>             'logFile' => '@runtime/logs/email.log',
>         ],
> ```
> 
> I suppose also other transport layers use a specific category when logging, probably you could log also those categories if you use something different.

Thank you. I have enabled the filetarget and do not see a file named `@runtime/logs/email.log`.

**Comment by WeeSee** [comment]
> Hi,
> you can also change the mailing configuration params with
> 
> > 'useFileTransport' => TRUE
> 
> in this way you can see in runtime/mail if usuario created the mail and also check the content.
> 
> For documentation refer to https://www.yiiframework.com/doc/guide/2.0/en/tutorial-mailing
> 
> PS: maybe it's better not to change the configuration of prod environment, I think it's better to use a test configuration

Thank you. I have enabled `useFileTransport`but there is no directory `@runtime/mail`but the file permissions of @runtime are `-rw-rw-rw-`

**Comment by maxxer** [comment]
Try using xdebug or some `die/echo` in the usuario code to see if you reach the mail sending parts...

**Comment by liviuk2** [comment]
> > Hi,
> > if you use swiftmailer you can redirect log messages to a file and analyse them, in log configuration you can add an entry like:
> > ```
> >         [
> >             'class' => 'yii\log\FileTarget',
> >             'logVars' => [], // system vars usually in this case are not so useful, you can avoid log them to get better readability
> >             'categories' => ['yii\swiftmailer\Logger::add'],
> >             'logFile' => '@runtime/logs/email.log',
> >         ],
> > ```
> > 
> > 
> > I suppose also other transport layers use a specific category when logging, probably you could log also those categories if you use something different.
> 
> Thank you. I have enabled the filetarget and do not see a file named `@runtime/logs/email.log`.

Did you checked that also the subdirectories of `@runtime` (`logs` and `mail`) have write permissions for the webserver user? 

You could try to write the code to send a custom mail just to see if the log is correctly written, then continue debugging usuarios part

**Comment by WeeSee** [comment]
Found the error. In `config/web.php` the mailer was configured as:

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => 'layouts/main-html',
            'textLayout' => 'layouts/main-text',

instead of 

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => '@app/mail/layouts/main-html',
            'textLayout' => '@app/mail/layouts/main-text',

The layout paths were wrong. So the Mailer could not render the messages and failed sending out emails since Yii2-usuario uses formatted emails. 

Everything works now.

**Comment by WeeSee** [comment]
Found the error. In `config/web.php` the mailer was configured as:

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => 'layouts/main-html',
            'textLayout' => 'layouts/main-text',

instead of 

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => '@app/mail/layouts/main-html',
            'textLayout' => '@app/mail/layouts/main-text',

The layout paths were wrong. So the Mailer could not render the messages and failed sending out emails since Yii2-usuario uses formatted emails. 

Everything works now.

**Comment by WeeSee** [comment]
Found the error. In `config/web.php` the mailer was configured as:

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => 'layouts/main-html',
            'textLayout' => 'layouts/main-text',

instead of 

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => '@app/mail/layouts/main-html',
            'textLayout' => '@app/mail/layouts/main-text',

The layout paths were wrong. So the Mailer could not render the messages and failed sending out emails since Yii2-usuario uses formatted emails. 

Everything works now.

**Comment by WeeSee** [comment]
Found the error. In `config/web.php` the mailer was configured as:

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => 'layouts/main-html',
            'textLayout' => 'layouts/main-text',

instead of 

    'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => false,
            'viewPath' => '@app/mail',
            'htmlLayout' => '@app/mail/layouts/main-html',
            'textLayout' => '@app/mail/layouts/main-text',

The layout paths were wrong. So the Mailer could not render the messages and failed sending out emails since Yii2-usuario uses formatted emails. 

Everything works now.
