### ISSUE TITLE
✉️ Disable send Welcome Email

### ISSUE THREAD

**Issue by gogl92** [2amigos/yii2-usuario#401]
### What steps will reproduce the problem?
If I do not set credentials for email, for example if I'm working in a local develop environment and I try to create a user.

### What is the expected result?

I should be able to disable the welcome email like:

```
'welcomeEmail` => false,
```

### What do you get instead?
 I got `Error Sending welcome message to {email}. Please try again later.`

**Comment by maxxer** [comment]
Why not setting `useFileTransport`to TRUE in Yii mailer config?

**Comment by maxxer** [comment]
I understand an additional config param in usuario can be useful as well, it was just a quick suggestion ;)

**Comment by gogl92** [comment]
@maxxer oh sounds like it can work, let me give it a try! 🚀

**Comment by gogl92** [comment]
@maxxer `file transport did the trick thanks! 👍🏼

**Comment by mkraibt** [comment]
is there a way to disable just the welcome email in production ?

**Comment by TimoB2005** [comment]
i have no e-mail server how should i do that?

**Comment by juppwerner** [comment]
I was using the command user/create in the console.
The error which stopped sending the email actually was found in the logfile runtime/logs/app.log:

2023-06-21 13:27:06 [-][-][-][error][usuario] Please configure UrlManager::scriptUrl correctly as you are running a console application.
2023-06-21 13:27:06 [-][-][-][error][usuario] Error sending welcome message to "joachim@jo-werner.de". Please try again later.

I assume the welcome email template uses the Url function, so in the console app we thus need to configure

config/console.php
 components > urlManager > scriptUrl, e.g. to something like 'http://127.0.0.1:8080'.

This was not so obvious, I hope it helps somebody.
