### ISSUE TITLE
Trying to get property 'enableGdprCompliance' of non-object

### ISSUE THREAD

**Issue by ofilin** [2amigos/yii2-usuario#403]
If using User model without module I have error "Trying to get property 'enableGdprCompliance' of non-object",

For fix:
if (**$this->module &&** $this->module->enableGdprCompliance) {

https://github.com/2amigos/yii2-usuario/blob/2504dd03b9b44971b783dde7c906757a63b14e79/src/User/Model/User.php#L167

**Comment by maxxer** [comment]
closing per no further comment
