### ISSUE TITLE
yiisoft/yii2-codeception

### ISSUE THREAD

**Issue by TerraSkye** [2amigos/yii2-usuario#41]
the package `yiisoft/yii2-codeception` is depricated in favor of using the official yii2 module of codeception.
so should we consider migrating?

**Comment by tonydspaniard** [comment]
Yes!

**Comment by TerraSkye** [comment]
currently don`t have the time to migrate it as i`m trying to learn how todo testing.
therefore i was checking out the way it was setup in here and saw the old package.

**Comment by tonydspaniard** [comment]
No problem @TerraSkye I'll do it. Thanks for pointing that out.

**Comment by tonydspaniard** [comment]
done @TerraSkye
