### ISSUE TITLE
Translations of the placeholders in the login widget

### ISSUE THREAD

**Issue by anapaulaxenon** [2amigos/yii2-usuario#419]
### What steps will reproduce the problem?
Instance LoginWidget::widget();

In file yii2-usuario/src/User/resources/views/widgets/login/form.php , the lines 38 and 40, returns placeholder without translations.

### What is the expected result?

    <?= $form->field($model, 'login')->textInput(['placeholder' => Yii::t('usuario', 'Login')]) ?>

    <?= $form->field($model, 'password')->passwordInput(['placeholder' => Yii::t('usuario', 'Password')]) ?>

### What do you get instead?

    <?= $form->field($model, 'login')->textInput(['placeholder' => 'Login']) ?>

    <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Password']) ?>

**Comment by maxxer** [comment]
Would you mind creating a pull request?
