### ISSUE TITLE
Error sending welcome message to "xxx@email.com". Please try again later.

### ISSUE THREAD

**Issue by TimoB2005** [2amigos/yii2-usuario#425]
### What steps will reproduce the problem?
run "yii user/create youremail@gmail.com admin adminadmin administrator"

### What is the expected result?
a working user.

### What do you get instead?
The Error:

> Please fix following errors:
> - Error sending welcome message to "email@email.de". Please try again later.
>

**Comment by TonisOrmisson** [comment]
seems like you have no e-mail transport configured

**Comment by TimoB2005** [comment]
so i created a migration with "yii migrate/create admincreation"

and puttet the code for an admin user in it. Does that need an E-Mail Transport?
Because the login with the login-details seems not to work
