### ISSUE TITLE
Error run migrations

### ISSUE THREAD

**Issue by pana1990** [2amigos/yii2-usuario#43]
### What steps will reproduce the problem?

deploy app in my server and i execute migrate command

### What is the expected result?

migrations migrate

### What do you get instead?

The following error : 

```
[RuntimeException]                                                                                                                           
  Error: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes                      
  The SQL being executed was: ALTER TABLE `social_account` ADD UNIQUE INDEX `idx_social_account_provider_client_id` (`provider`, `client_id`) 
```

This happen because the migrations hasn't set tableOptions to innodb, then it use engine by default.

Sometimes i can't change engine by default in my server, it posible include some like this one : 

https://github.com/dektrium/yii2-user/blob/master/migrations/Migration.php#L39

**Comment by tonydspaniard** [comment]
@pana1990 thanks for this. Yes, we should integrate that. I'll handle it asap if you don't have time for PR

**Comment by pana1990** [comment]
I can handle this weekend, do not worry

**Comment by tonydspaniard** [comment]
Fixed on https://github.com/2amigos/yii2-usuario/commit/b72abab0ee2c14e245821cc6636fa32a32073aa8 (forgot to put the hash sign)
