### ISSUE TITLE
problem in user/admin/create

### ISSUE THREAD

**Issue by pana1990** [2amigos/yii2-usuario#44]
### What steps will reproduce the problem?
1º I go /user/admin/create
2º I fill out email and username (password empty)
3º Click in Save

### What is the expected result?

Generate password for my new user.

### What do you get instead?

Password empty.

It is beacuse password send empty value and this check not works

https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/UserCreateService.php#L51

@tonydspaniard Can i send pr?

**Comment by tonydspaniard** [comment]
@pana1990 you don't need to ask for PRs. All your efforts are **highly** appreciated and welcome.

**Comment by tonydspaniard** [comment]
I wonder if we should 'trim' the password too attribute too.
