### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by WeeSee** [2amigos/yii2-usuario#440]
In this line

https://github.com/2amigos/yii2-usuario/blob/master/src/User/Controller/AdminController.php#L294

    if ($this->make(UserBlockService::class, [$user, $event, $this])->run()) {

there is an instance of class `UserBlockService` created with three parameters ´$user, $event, $this´.

But in the constructor of the class `UserBlockService` 

https://github.com/2amigos/yii2-usuario/blob/504e18c855be619f2e4812f06f43a824370644f6/src/User/Service/UserBlockService.php#L27

    public function __construct(
        User $model,
        UserEvent $event,
        AdminController $controller,
        SecurityHelper $securityHelper
    ) {
        $this->model = $model;
        $this->event = $event;
        $this->controller = $controller;
        $this->securityHelper = $securityHelper;
    }

four parameters are required. Where does `$securityHelper` get it's value from?

How does this work?

**Comment by TonisOrmisson** [comment]
di container
```
            // helpers
            $di->set(Helper\AuthHelper::class);
            $di->set(Helper\GravatarHelper::class);
            $di->set(Helper\SecurityHelper::class);
            $di->set(Helper\TimezoneHelper::class);

```
https://github.com/2amigos/yii2-usuario/blob/master/src/User/Bootstrap.php#L93
