### ISSUE TITLE
Implicit conversion

### ISSUE THREAD

**Issue by srakl** [2amigos/yii2-usuario#461]
### What steps will reproduce the problem?

I'm using PHP 8.1

When i go to the profile setting page, i get this error

`Implicit conversion from float 12.75 to int loses precision`

Looks like the error is from `$timezoneHelper->getAll()` located here

```
 <?= $form
                        ->field($model, 'timezone')
                        ->dropDownList(ArrayHelper::map(
                                                        $timezoneHelper->getAll(), 'offset', 'name'
                                                    ), 
                                                    [
                                                        'prompt' => 'Select Timezone', 
                                                        'options' => [ '' => ['Selected'=>'selected']], 
                                                        'class' => 'custom-select custom-select-lg'
                                                    ]
                                        );
                    ?>
```

Any ideas on how to fix this? Thanks

**Comment by maxxer** [comment]
I only see a division here:

https://github.com/2amigos/yii2-usuario/blob/43b2d76ec6a5719c69f0713ffc6a60dcb23467da/src/User/Helper/TimezoneHelper.php#L35

Could it be there's a TZ causing it?

**Comment by srakl** [comment]
@maxxer I added a `print_r($timeZones); die;` to live 42 and got this

```
...
...
...
389 => [
        'timezone' => 'Pacific/Chatham'
        'name' => 'Pacific/Chatham (UTC +12.75)'
        'offset' => 12.75
    ]
```

division of float maybe?

**Comment by maxxer** [comment]
What is the exact exception you get? I cannot see where it attempts to cast this value to int.

**Comment by maxxer** [comment]
Maybe? Just a guess,  `SORT_NUMERIC` should do with floats

https://github.com/2amigos/yii2-usuario/blob/43b2d76ec6a5719c69f0713ffc6a60dcb23467da/src/User/Helper/TimezoneHelper.php#L43

**Comment by srakl** [comment]
@maxxer 

It fails in this `view`

```
 <?= $form
                        ->field($model, 'timezone')
                        ->dropDownList(ArrayHelper::map(
                                                        $timezoneHelper->getAll(), 'offset', 'name'
                                                    ), 
                                                    [
                                                        'prompt' => 'Select Timezone', 
                                                        'options' => [ '' => ['Selected'=>'selected']], 
                                                        'class' => 'custom-select custom-select-lg'
                                                    ]
                                        );
                    ?>
```

in `ArrayHelper::map()`  maybe ?

**Comment by maxxer** [comment]
Unlikely. Out of curiosity, try changing line 35 of [TimezoneHelper.php](https://github.com/2amigos/yii2-usuario/blob/43b2d76ec6a5719c69f0713ffc6a60dcb23467da/src/User/Helper/TimezoneHelper.php#L35) to something like this:

```php
$offset = $date->getOffset() / 60 / 60 * 100; 
```

**Comment by maxxer** [comment]
Look [here](https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string#array-keys).

We should manage `offset` as string instead of `float`, otherwise it cannot be used as array key. So you were right, the problem happens at `ArrayHelper::map`. Can you create a pull request?

**Comment by maxxer** [comment]
Note: when converting the float to string, remember to  `str_pad` the value or sorting will be messed up

**Comment by maxxer** [comment]
should be closed, if you can have a test run
