### ISSUE TITLE
Invalid login url in module bootstrap

### ISSUE THREAD

**Issue by vahan-garnikyan** [2amigos/yii2-usuario#5]
It seems in bootstrap file you have  defined old auth action rule

```
$di->set(
     'yii\web\User',
     [
          'enableAutoLogin' => true,
          'loginUrl' => ['/user/auth/login'],
          'identityClass' => $di->get(ClassMapHelper::class)->get(User::class),
     ]
);
```

`'loginUrl' => ['/user/auth/login'],`

must be changed to

`'loginUrl' => ['/user/security/login'],`

**Comment by tonydspaniard** [comment]
@vahan-garnikyan thanks!

**Comment by tonydspaniard** [comment]
Fixed... wrong issue number on commit
