### ISSUE TITLE
Getting errors when encoded with IonCube

### ISSUE THREAD

**Issue by pappfer** [2amigos/yii2-usuario#57]
I have to deliver a Yii2 app to a client encoded with IonCube. Unfortunately it's not enough to encode my code, but I also have to encode the whole `/vendor` folder as well, because otherwise the default parameters won't work. See more about it here: http://www.yiiframework.com/forum/index.php/topic/34266-strange-behavior-of-yii-when-the-code-is-encoded-ioncube/

When I encode the entire project I get an error related to yii2-usuario, see the attached screenshot.
![kepernyokep errol 2017-08-11 16-38-38](https://user-images.githubusercontent.com/738623/29220203-a3a7ba96-7eba-11e7-98ce-73b34127e395.png)

**Comment by tonydspaniard** [comment]
@pappfer Thanks for your feedback but I believe this is totally unrelated to the module but to framework itself? Do you have other modules? is only happening with usuario? I have never faced that issue so I am not that good of a help.

**Comment by pappfer** [comment]
I don't think it is related to the framework itself, because the encoded project works if I don't use any modules. I do have other modules installed as well, but as you can see on the screenshot the error is about yii2-usuario module.
However I totally understand that this is not something you would like to investigate or work on, because your module works just fine if I don't encode it, and I also don't expect you to do that at all, so I'm closing my issue and trying to fix it myself somehow.

**Comment by tonydspaniard** [comment]
Have you tried with another module? A simple one so to test is related to usuario or is subject to the modules config used by Yii?
