### ISSUE TITLE
Profile query search by user_id

### ISSUE THREAD

**Issue by vahan-garnikyan** [2amigos/yii2-usuario#6]
In Da\User\Query\ProfileQuery

```
public function whereId($id)
    {
        return $this->andWhere(['user_id' => $id]);
    }
```
Instead of
```
public function whereId($id)
    {
        return $this->andWhere(['id' => $id]);
    }
```

**Comment by tonydspaniard** [comment]
@vahan-garnikyan do you have time for a pull request?

**Comment by vahan-garnikyan** [comment]
https://github.com/2amigos/yii2-usuario/blob/master/src/User/Controller/SettingsController.php#L107

You use there user_id form profile search. That's normal, no one needs search by profile id. So to make ProfileQuery->whereId to work there are 2 options.

1. Change andWhere(['id' => $id]) to andWhere(['user_id' => $id])
2. Or make new scope whereUserId for profileQuery

**Comment by tonydspaniard** [comment]
Fixed Thanks for your pull request :)
