### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by whisere** [2amigos/yii2-usuario#63]
followed the instruction here: http://yii2-usuario.readthedocs.io/en/latest/
and composer require 2amigos/yii2-usuario:~1.0
also try @dev and change stability to dev,

https://github.com/2amigos/yii2-selectize-widget/issues/36
still reports the same error above

sorry accidentally posted to yii2-selectize-widget, but it is relevant to both I guess...

**Comment by tonydspaniard** [comment]
Add this to your composer and tell me how it goes: 

```json 
"minimum-stability": "dev",
"prefer-stable": true,
```

**Comment by whisere** [comment]
Thank you! I have tried but it still reported the same:

  Problem 1
    - 2amigos/yii2-usuario 1.0.0 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.0-beta requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.1 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.10 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.11 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.12 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.13 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.2 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.3 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.4 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.5 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.6 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.7 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.8 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-usuario 1.0.9 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.x-dev].
    - 2amigos/yii2-selectize-widget 1.0.x-dev requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.3 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.2 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.1 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.0 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - Installation request for 2amigos/yii2-usuario ~1.0 -> satisfiable by 2amigos/yii2-usuario[1.0.0, 1.0.0-beta, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by whisere** [comment]
requires bower-asset/selectize ~0.12.0 -> no matching package found.

Not sure if this is the cause, can't find bower-asset/selectize in packagist?
 https://packagist.org/search/?q=bower-asset%2Fselectize

**Comment by tonydspaniard** [comment]
@whisere I think I am going to modify that widget and use our recent select2.

**Comment by whisere** [comment]
That sounds great, thank you! Please let me know when it is ready to use. :)

**Comment by sinfuljosh** [comment]
By any chance is this related to yiisoft moving away from [fxp-asset](https://github.com/fxpio/composer-asset-plugin) and started using [asset-packagist](https://github.com/hiqdev/asset-packagist) ? 

Trying to fully understand this as well. :)

**Comment by tonydspaniard** [comment]
@sinfuljosh no, it has nothing to do. I believe is an issue with Selectize itself

**Comment by sinfuljosh** [comment]
I figured it out, in a way it is related to my earlier comment. 

The current versions of Yii2 have removed the requirement for fxp/composer-asset-plugin to be installed. Many of the guides for installing Yii2 mention the command below because it is no longer needed for the core Yii2 framework.

`composer global require "fxp/composer-asset-plugin:~1.3" `

Your selectize widget still depends on the above package to be installed to load the bower-asset/selectize, otherwise the error's seen in the original post occur. 

I made a fork of your selectize widget with the adjustments to make use of the asset-packagist.org method now being used by yiisoft and this resolved the issue. 

https://github.com/sinfuljosh/yii2-selectize-widget  

The only change was to the [composer.json](https://github.com/2amigos/yii2-selectize-widget/compare/master...sinfuljosh:master)

in regards to the change in the install path, more information can be found here https://asset-packagist.org/site/about about two methods to address this, yiisoft uses the alias method btw.

**Comment by tonydspaniard** [comment]
Thanks @sinfuljosh

**Comment by tonydspaniard** [comment]
Updating selectize

**Comment by whisere** [comment]
I tried the same install, it still reported the error, is there other way to install? or any change here: http://yii2-usuario.readthedocs.io/en/latest/
it seems still using bower-asset/selectize ?

composer require 2amigos/yii2-usuario:~1.0

 - 2amigos/yii2-usuario 1.0.9 requires 2amigos/yii2-selectize-widget ~1.0 -> satisfiable by 2amigos/yii2-selectize-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.0.x-dev].
    - 2amigos/yii2-selectize-widget 1.0.x-dev requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.1.0 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.4 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.3 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.2 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.1 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - 2amigos/yii2-selectize-widget 1.0.0 requires bower-asset/selectize ~0.12.0 -> no matching package found.
    - Installation request for 2amigos/yii2-usuario ~1.0 -> satisfiable by 2amigos/yii2-usuario[1.0.0, 1.0.0-beta, 1.0.1, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].

composer. require 2amigos/yii2-selectize-widget:~1.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for 2amigos/yii2-selectize-widget ~1.1 -> satisfiable by 2amigos/yii2-selectize-widget[1.1.0].
    - 2amigos/yii2-selectize-widget 1.1.0 requires bower-asset/selectize ~0.12.0 -> no matching package found.

**Comment by whisere** [comment]
Okay need to add this to the composer.json file under my project too:
"repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
It worked after adding this.
Thanks!

**Comment by tonydspaniard** [comment]
@whisere is that on this composer or project composer?

**Comment by whisere** [comment]
I added it under my project composer but I suspect it might work too under the module composer.

**Comment by tonydspaniard** [comment]
@whisere 
> I added it under my project composer but I suspect it might work too under the module composer.

I believe that for the project is required that setting if you have not. It doesn't apply to extensions (widgets or modules) as it does not override the parent's. We use our extensions on our everyday work and no issues.

**Comment by whisere** [comment]
Thank you for all your help :)
