### ISSUE TITLE
Provide different module layout params for admin and public controllers

### ISSUE THREAD

**Issue by naffiq** [2amigos/yii2-usuario#64]
### What steps will reproduce the problem?
I'm trying to apply different layouts for public controllers and administrating ones

### What is the expected result?
It should be easier to setup different layouts

### What do you get instead?
I have to override controllers or use DiC for that in bootstrap process

Maybe it'll be better to separate modules for administrating users and public controllers? (login, register etc)

**Comment by tonydspaniard** [comment]
@naffiq I did that for my current project and I agree with you about its complexity.  Separating modules is what I did using yii2-usuario to offer a super admin and site user panels: 

```php 
'controllerMap' => [
        'admin' => [
            'class' => '\admin\controllers\AdminController',
        ],
        'profile' => [
            'class' => '\panel\controllers\ProfileController',
        ],
        'settings' => [
            'class' => '\panel\controllers\SettingsController',
        ],
    ]
```
As you can see in the above code, different controllers are located on different locations as I have the super admin using the `AdminController` and then panel (other module) for the other overridden controllers. 

Then what I did is to configure the layout on the `AdminController::beforeAction`: 

```php 
class AdminController extends \Da\User\Controller\AdminController
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        $this->layout = '@admin/views/layouts/main';

        return parent::beforeAction($action);
    }
```
Finally, configured the `View` component's `theme` attribute to look on different places (where views are overridden: 

```php 
'components' => [
     'view' => [
              'theme' => [
                  'pathMap' => [
                      '@Da/User/resources/views' => [
                           '@admin/views',
                           '@panel/views',
                           '@app/modules/user/views' 
                   ]
                ],
         ],
    ]
]
```

I know is a too much but I think is up to the developer to structure the application to suit his needs and requirements (as I did above) and I believe the module does a good job currently.  I personally do not think the module should be splitted in two.

**Comment by tonydspaniard** [comment]
I think my answer solves the problem. Let me know if it doesn't.
