### ISSUE TITLE
Incorrect event type in RegistrationController?

### ISSUE THREAD

**Issue by Philosoft** [2amigos/yii2-usuario#68]
### What steps will reproduce the problem?

Try to listen to `UserEvent::EVENT_AFTER_REGISTER` at `RegistrationController`

```php
Event::On(
    RegistrationController::class,
    UserEvent::EVENT_AFTER_REGISTER,
    function (UserEvent $event) {
    }
);
```

### What is the expected result?
`$event` inside anonymous function is instance of `UserEvent`

### What do you get instead?
`$event` is `FormEvent`

### Additional comments

this range in [`RegistrationController`](https://github.com/2amigos/yii2-usuario/blob/master/src/User/Controller/RegistrationController.php#L97-L116):
* first highlighted line - creation of `FormEvent`
* last highlighted line - trigger of `UserEvent::EVENT_AFTER_REGISTER` with `FormEvent` instead of `UserEvent`

so, we'll get an error despite our actions to be taken perfectly according to [documentation](https://github.com/2amigos/yii2-usuario/blob/master/docs/events/user-events.md):
> All these events receive an instance of `Da\User\Event\UserEvent`. The Event receives an instance of a  `Da\Model\User` class that you could use for whatever logic you wish to implement.

**Comment by tonydspaniard** [comment]
You are totally right, and there is a problem with the flow. I think it should fire a `FormEvent` instead, providing the `RegistrationForm`. That way, the event could get the attributes prior registration and later the `User` model itself. 

A `UserEvent` needs a `User` and that is not happening until is actually registered/created (https://github.com/2amigos/yii2-usuario/blob/master/src/User/Controller/RegistrationController.php#L104). The user event should be triggered where it is currently: https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/UserRegisterService.php#L57

I will make the changes for the Controller to trigger a FormEvent (will modify the documentation too). Thank you very much for this issue report.

**Comment by Philosoft** [comment]
Glad I can help)

Also [here](https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/UserRegisterService.php#L57) type of event will be `\yii\base\Event` instead of `UserEvent`, so there will be no `getUser` method inside (of course we can get model by `$event->sender`, but still)

**Comment by tonydspaniard** [comment]
I wasn't thinking to modify the `UserRegisterService` but the controller. Why do you think is required? I need more info.. I'll check on these on the wknd. This week I have far too much work 😞

**Comment by Philosoft** [comment]
I just suggest to adjust documentation accordingly)
