### ISSUE TITLE
Log level when user can't register

### ISSUE THREAD

**Issue by MKiselev** [2amigos/yii2-usuario#69]
In some places used Error log level when logging e.g.
https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/PasswordRecoveryService.php#L65
https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/UserCreateService.php#L72

But here: https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/UserRegisterService.php#L81 is set Warning level.

I think better set also Error level.

**Comment by tonydspaniard** [comment]
Agreed... have time for a pr? Mind also adding your fix on the change log file. Thanks!

**Comment by tonydspaniard** [comment]
@MKiselev I have deleted the prior comment, but I agree with your statement. If you have time for a PR that would be awesome. If you do, please do not forget to update the change log.
