### ISSUE TITLE
[New setup] Migration error

### ISSUE THREAD

**Issue by Thoulah** [2amigos/yii2-usuario#71]
### What steps will reproduce the problem?
php yii migrate

### What is the expected result?
Success :)

### What do you get instead?
```
Yii Migration Tool (based on Yii v2.0.13-dev)

Creating migration history table "api_migration"...Done.
Total 5 new migrations to be applied:
	Da\User\Migration\m000000_000001_create_user_table
	Da\User\Migration\m000000_000002_create_profile_table
	Da\User\Migration\m000000_000003_create_social_account_table
	Da\User\Migration\m000000_000004_create_token_table
	Da\User\Migration\m000000_000005_add_last_login_at

Apply the above migrations? (yes|no) [no]:yes
*** applying Da\User\Migration\m000000_000001_create_user_table
    > create table {{%user}} ... done (time: 0.007s)
    > create unique index idx_user_username on {{%user}} (username) ... done (time: 0.006s)
    > create unique index idx_user_email on {{%user}} (email) ... done (time: 0.007s)
*** applied Da\User\Migration\m000000_000001_create_user_table (time: 0.026s)

*** applying Da\User\Migration\m000000_000002_create_profile_table
    > create table {{%profile}} ... done (time: 0.008s)
    > add foreign key fk_profile_user: {{%profile}} (user_id) references {{%user}} (id) ... done (time: 0.014s)
*** applied Da\User\Migration\m000000_000002_create_profile_table (time: 0.027s)

*** applying Da\User\Migration\m000000_000003_create_social_account_table
    > create table {{%social_account}} ... done (time: 0.006s)
    > create unique index idx_social_account_provider_client_id on {{%social_account}} (provider,client_id) ... done (time: 0.009s)
    > create unique index idx_social_account_code on {{%social_account}} (code) ... done (time: 0.018s)
    > add foreign key fk_social_account_user: {{%social_account}} (user_id) references {{%user}} (id) ...Exception: SQLSTATE[HY000]: General error: 1005 Can't create table 'db646148637.#sql-59d_6d902d' (errno: 121)
The SQL being executed was: ALTER TABLE `api_social_account` ADD CONSTRAINT `fk_social_account_user` FOREIGN KEY (`user_id`) REFERENCES `api_user` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT (/homepages/htdocs/yii/vendor/yiisoft/yii2/db/Schema.php:595)
#0 /homepages/31/d646147665/htdocs/yii/vendor/yiisoft/yii2/db/Command.php(973): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `ap...')
#1 /homepages/htdocs/yii/vendor/yiisoft/yii2/db/Migration.php(446): yii\db\Command->execute()
#2 /homepages/htdocs/yii/vendor/2amigos/yii2-usuario/src/User/Migration/m000000_000003_create_social_account_table.php(53): yii\db\Migration->addForeignKey('fk_social_accou...', '{{%social_accou...', 'user_id', '{{%user}}', 'id', 'CASCADE', 'RESTRICT')
#3 /homepages/htdocs/yii/vendor/yiisoft/yii2/db/Migration.php(115): Da\User\Migration\m000000_000003_create_social_account_table->safeUp()
#4 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(713): yii\db\Migration->up()
#5 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(193): yii\console\controllers\BaseMigrateController->migrateUp('Da\\User\\Migrati...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/Controller.php(135): yii\base\Controller->runAction('', Array)
#10 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#11 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate', Array)
#12 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate', Array)
#13 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /homepages/htdocs/yii/api/yii(15): yii\base\Application->run()
#15 {main}
*** failed to apply Da\User\Migration\m000000_000003_create_social_account_table (time: 0.046s)


2 from 5 migrations were applied.
```

**Comment by tonydspaniard** [comment]
@Thoulah have you followed all instructions? You also need to make sure the initial migrations of Yii are not applied.

**Comment by Thoulah** [comment]
```
'controllerMap' => [
	'migrate' => [
		'class' => \yii\console\controllers\MigrateController::class,
		'migrationNamespaces' => [
			'Da\User\Migration',
		],
	],
],
```
That is in my console.php. No other migrations have run (no tables are present prior to this migration)

**Comment by tonydspaniard** [comment]
There is something really strange @Thoulah and is the name of your third table: 

- what exactly is `api_social_account`???  is your table prefix `api_`?

**Comment by Thoulah** [comment]
My table prefix is indeed `api_`

Running the SQL leads to: `#1005 - Can't create table 'db646148637.#sql-59d_bf746' (errno: 121)`

Googled it now, the error is because "You will get this message if you're trying to add a constraint with a name that's already used somewhere else".
I am using another YII installation in the same database (with another table prefix), which obviously uses the same constraint name. Sorry about that :(
I am leaving this note in case anyone runs into the same error.

On a sidenote: is there a way to have this module use a different table prefix, in case you want another website use the same user data?

**Comment by tonydspaniard** [comment]
@Thoulah glad you found the issue. There should be not problem if you wish a table prefix. The extension already assumes that.

**Comment by Thoulah** [comment]
Thanks for your answer. I see my question was a bit too vague. I am looking for something like this:

```
	'modules' => [
		'user' => [
			'class' => Da\User\Module::class,
			'tablePrefix' => 'otherPrefix_', //other than the one in `db`
		],
	],
```

Is that possible?

**Comment by tonydspaniard** [comment]
Nope... the table prefix has to be configured on the `db` component configuration.

**Comment by tonydspaniard** [comment]
All models work with placeholders (https://github.com/2amigos/yii2-usuario/blob/master/src/User/Model/User.php#L112) if you find an issue with that. Let me know, I'll fix it.

**Comment by Thoulah** [comment]
I have no issues with that, just a wish. Can I make this a feature request?

I have one website prefix `website_` and one with `api_` in the same database. It would be cool if I could have them both use the same user tables `user_` for example.

**Comment by Thoulah** [comment]
Should I make a separate Issue for this feature request?

**Comment by tonydspaniard** [comment]
> It would be cool if I could have them both use the same user tables user_ for example.

When you work with two different prefixes it means that you haven't set the table prefix on your db component. Why not leaving the table names as they are?

**Comment by Thoulah** [comment]
It's 2 different websites, each with its own prefix.

**Comment by tonydspaniard** [comment]
> It's 2 different websites, each with its own prefix.

Sharing the same database? If that is the case and you wish to create a SSO, I highly recommend you to have a different DB for user (you can have multiple `db` components as long as you change its key name). Then, make sure you override all models so their `public static function getDb()` returns the database where the usuario module is set (ie `return Yii::$app->get('userDb')`.

**Comment by Thoulah** [comment]
Thank you, I will look into that.

If I need to overwrite models anyway, I might as well just return a different tableName
