### ISSUE TITLE
How to create a user without accessing the administrator panel

### ISSUE THREAD

**Issue by GiorgiaMenozzi** [2amigos/yii2-usuario#72]
Before asking I need to explain (hoping in a clear and concise way) my problem.
In my project I have an Anagrafica model (with anagraphic info such as email, name, surname..) that is connected to the user table. In the user table I have added a column with a foreign key pointing to the primary key of my model (idanagrafica in the anagrafica table).
I've also created a model (called Utente) that extends Da\User\Model\User adding functions and relations. 
I need that the actionCreate of the Anagrafica model can also create a user just like with user/admin/create.
I think I have to create in the UtenteController a function createUtente similar to the user/admin/create that will simply create a new user with 3 parameters (the email, the idanagrafica of my Anagrafica model and a password) without redirect.
I'm quite new to yii2 and I have to admit that I don't know how to modify your function in order to reach that goal.

Thank you in advance for any help (hoping my explanation is clear enough)

**Comment by tonydspaniard** [comment]
Have you tried with the console commands provided? http://yii2-usuario.readthedocs.io/en/latest/installation/console-commands/

**Comment by GiorgiaMenozzi** [comment]
You mean using the exec function?  thank you! I'm gonna try

**Comment by tonydspaniard** [comment]
@GiorgiaMenozzi wait.... I think I didn't read carefully enough your question. You simply need to override the Controller's action. Check this section: http://yii2-usuario.readthedocs.io/en/latest/enhancing-and-overriding/overriding-controllers/

Add the action you wish to override (ie `user/admin/create => AdminController::create`) and that's it.

**Comment by GiorgiaMenozzi** [comment]
Thank you for your help!
I've bypassed the problem creating a function in the UtenteController with parts of your run function of the UserCreateService class.
I think that I need  more practice with yii2 to really understand how to override your action (don't know how to avoid the error "Using $this when not in object context" at the very first row )

**Comment by tonydspaniard** [comment]
For that we will require a bit of info... like code? Best
