### ISSUE TITLE
How can we access admin/role/rule etc pages after creating a user (via signup)

### ISSUE THREAD

**Issue by whisere** [2amigos/yii2-usuario#75]
Can't find instruction about how to make a user admin?
it says Forbidden (#403) when accessing user/admin
try  adding       'admins' => ['your-username-goes-here'] as stated:
https://github.com/dektrium/yii2-user/blob/master/docs/user-management.md
but reported Unknown Property – yii\base\UnknownPropertyException Setting unknown property: Da\User\Module::admins

**Comment by tonydspaniard** [comment]
@whisere the documentation you pointed is not for this module. The good documentation is here: http://yii2-usuario.readthedocs.io/en/latest/#getting-started. The property on this module is: http://yii2-usuario.readthedocs.io/en/latest/installation/configuration-options/

**Comment by whisere** [comment]
Thank you, took a while to figure out added 'administrators' => ['username'] in module setting, finally can access those pages for the first user, (it might be good to add these to the instruction too..):
'modules' => [
        
        'user' => [
            'class' => Da\User\Module::class,
            'administrators' => ['username']
        ]
    ],

**Comment by ajmedway** [comment]
@tonydspaniard yes I agree, I had to dig around core code, some enhanced documentations would be useful to illustrate how to configure the first admin

**Comment by tonydspaniard** [comment]
@ajmedway agree, unfortunately I do not have much time nowadays. A bit of help would be highly appreciated

**Comment by ajmedway** [comment]
@tonydspaniard sure! I will see if I can find some time to make such enhancements to the documentation in due course to help out :)
