### ISSUE TITLE
can't run on php 5.4 as  yii2.0?

### ISSUE THREAD

**Issue by whisere** [2amigos/yii2-usuario#77]
It seems have problem under php5.4

reported 
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

on 'user' => [
            'class' => Da\User\Module::class,

It is okay under php7. yii2.0 supports php5.4 though..
any suggestions for server running php5.4 without update? Thanks!

**Comment by TerraSkye** [comment]
upgrade the server.

**Comment by mrbig00** [comment]
The class keyword was introduced in [php 5.5](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) and the composer clearly states that this project requires php 5.5

**Comment by tonydspaniard** [comment]
@whisere take the advice of @TerraSkye and @mrbig00 and upgrade the server and to be honest, I would use PHP 7+ not less. Not because of the module, but for the advantages it has.

**Comment by tonydspaniard** [comment]
@whisere the other solution is that you transform this app to run on that version. For example, replace the "::class" to a full string namespace.

**Comment by whisere** [comment]
Thank you, will try that, try get_class to see if it works..

**Comment by whisere** [comment]
It seems I have made it work by making the following change:
yii base object has the function className() already
http://www.yiiframework.com/doc-2.0/yii-base-object.html#className()-detail

so for class that is extend from yii object change as following:
::class)-> ::className())
::class, -> ::className(),
::class; -> ::className();
::class] -> ::className()]

for the class that is not, add the function in its file:
/**
     * Returns the fully qualified name of this class.
     * @return string the fully qualified name of this class.
     */
    public static function className()
    {
        return get_called_class();
    }
And change its invoke of ::class to ::className()

**Comment by whisere** [comment]
I did a full folder (exclude doc folder) replace of 
::class)-> ::className())
::class, -> ::className(),
::class; -> ::className();
::class] -> ::className()]
first and then the rest is easy too, just check which class reports error from ::className then do the second step. hope this helps others with the same need..

**Comment by tonydspaniard** [comment]
@whisere thank you for showing your solution here.

**Comment by whisere** [comment]
No problem at all :) thanks for your help too.

**Comment by TerraSkye** [comment]
php 5.4 has end of life already, so it is vulnerable for know security issues
my advice is to upgrade asap, as your projects are at risk, and so is the user content at it.

**Comment by whisere** [comment]
will certainly try that as soon/as much as I can.
