### ISSUE TITLE
Implement User factory

### ISSUE THREAD

**Issue by mrbig00** [2amigos/yii2-usuario#78]
It would be a nice and handy feature to have a user factory. 

Imagine these use cases:

- Creating users from cli
- Creating users from rest api's

**Comment by tonydspaniard** [comment]
Thanks @mrbig00 on the cli we have: https://github.com/2amigos/yii2-usuario/blob/master/src/User/Command/CreateController.php 

And, whilst I agree with you on Factory, the module is using extensively Yii2's DI. What is the Factory class bring vs this approach: https://github.com/2amigos/yii2-usuario/blob/master/src/User/Command/CreateController.php#L29 ?

**Comment by mrbig00** [comment]
The current implementation is pretty nice and clean. But  it's not as straightforward as it would be implemented in a factory like the Mail, Token, etc. 

But I think that you're right, the whole extension is extensively built around Yii's DI and stepping on a different path in this stage is a pretty dumb idea :smile:

**Comment by tonydspaniard** [comment]
> But it's not as straightforward as it would be implemented in a factory like the Mail, Token, etc.

I agree with you. TBH I even thought about it but inclined to use DI to avoid helper classes as much as possible and make use of automatic instance injection on the class __construct methods. 

Thanks for bringing this conversation up and your interest on the module.
