### ISSUE TITLE
Enhancements to Mailer exception handling and events

### ISSUE THREAD

**Issue by kartik-v** [2amigos/yii2-usuario#79]
Great user module. Some suggestions. Let know, will try and see if I can help with a PR.

## Affected code lines are below:

https://github.com/2amigos/yii2-usuario/blob/409d6f334ce43d8ff19eb0d4669cc83e35dd99d4/src/User/Controller/AdminController.php#L134-L141
 
## Suggestions:

1. Exception handling of mailer service - (e.g. using try catch or implement exception handling at the mailer service level) at the mailer service calls. With the current code, there is no visual  feedback back to the user interface for any MAILER error. 

2. Trigger an alert message when mailer service fails. Currently there is no `else` condition when `UserCreateService` fails.

SUGGESTED code change below:

```php
if ($this->make(UserCreateService::class, [$user, $mailService])->run()) {
	Yii::$app->getSession()->setFlash('success', Yii::t('usuario', 'User has been created'));
	$this->trigger(UserEvent::EVENT_AFTER_CREATE, $event);

	return $this->redirect(['update', 'id' => $user->id]);
} else {  // ADD A CONDITION FOR ALERTING USER
	Yii::$app->getSession()->setFlash('danger', Yii::t('usuario', 'Error creating user.')); 
	// it is better if the message can include actual details/reasons for failure via exception handling
}
```

**Comment by tonydspaniard** [comment]
Thanks @kartik-v this is a known issue. Any help highly appreciated.

**Comment by kartik-v** [comment]
Sure ... Will try and help

**Comment by tonydspaniard** [comment]
@kartik-v I have been thinking and I believe the biggest issue is with the mailer miss configuration. If by any chance the user creation has any errors, it will display on the form. 

My doubt is, should the mailer simply fail? That is, should we simply throw the error once catched? 

```php 
catch (Exception $e) {
            $transaction->rollBack();
            $this->logger->log($e->getMessage(), Logger::LEVEL_ERROR);

            throw $e;  // trigger the error 
            // return false;  // remove this
        }
```
If its a miss-configuration developer should know. If any other reason, the developer should override the controller's action and act according to its needs (if its private app, let error be triggered and handled by the page, if its a public app, then create the appropriate response) 

What do you think?

**Comment by kartik-v** [comment]
Yes... I agree - most of the issues should be with mailer misconfiguration. It can also be due to the mailer service configured working but misbehaving after sometime.

- *For the developer:* Yes if the exception is trapped and logged the developer would know what to take action
- *For the end user:* A right message (e.g. a danger alert via Session Flash) to show that the transaction has failed. (the transaction rollback is correctly needed).

**Comment by tonydspaniard** [comment]
So, should we simply trigger the error? Any other suggestion?

**Comment by kartik-v** [comment]
I was checking on the best approach to do this... and was thinking on ways to do this before submitting a PR. Somehow feel the following is to be done:

- Trap exception in the mailer service. In the following call in `AdminController`:   `$this->make(UserCreateService::class, [$user, $mailService])->run()` - I feel it must allow rolling back of transaction when mailer error/exception is thrown
- When error is received above an `else`condition to be included in the admin controller create action to alert the end user with a generic message.

```php
Yii::$app->getSession()->setFlash('danger', Yii::t('usuario', 'Error creating user.')); 
````

**Comment by kartik-v** [comment]
So to achieve the above - the mailer service errors should be separated than the user create service...

**Comment by kartik-v** [comment]
I propose the following - can the UserCreateService and all other such services that use mailers... return the following status codes instead of a boolean `true` or `false`. If so then we can have the actions in the Controller for the developer to handle them:

- `TRAN_SUCCESS` 
- `TRAN_ERROR`
- `MAIL_SUCCESS` 
- `MAIL_ERROR`

**Comment by tonydspaniard** [comment]
That could make the controller's actions a bit messy as we will be forced to react according to its result. 

What if we trigger an specific event? Like, having `Error::class` model that will be triggered and notify user that something bad happened on internal processes? - brainstorming

**Comment by kartik-v** [comment]
Yes.... Had mentioned about augmenting this by triggering events and it should be a valid solution assuming it passes all relevant handles and params for the developer to handle.  Do you think creating a separate events for mailer as well would be better? Something like 

- BEFORE_SEND_MAIL 
- SUCCESS_SEND_MAIL
- ERROR_SEND_MAIL

**Comment by tonydspaniard** [comment]
I think that would be awesome. And we could do: 

* BEFORE_SEND_MAIL
* AFTER_SEND_MAIL

With a `MailEvent` that could have the type of mail `welcome, confirmation, reset, etc...` and the result of its action (i.e. a `getError()` method could return null or an `Exception` instance.

**Comment by kartik-v** [comment]
PR #88 submitted

**Comment by tonydspaniard** [comment]
Excellent! Thank you for your time on this project.
