### ISSUE TITLE
How i can install this module?

### ISSUE THREAD

**Issue by ricar2ce** [2amigos/yii2-usuario#8]
me parece muy interesante este modulo, pero no se como instalarlo, por ejemplo donde lo ubico, que es Da?
disculpen mi ignorancia

**Comment by tonydspaniard** [comment]
Hola @ricar2ce ! 

Estoy intentando terminar la documentación pero es muy extensa. `Da` es parte del `namespace` y significa `dos amigos`. 

La documentación está en: http://yii2-usuario.readthedocs.io/en/latest/ pero lamentablemente en inglés.

**Comment by tonydspaniard** [comment]
@ricar2ce documentación terminada

**Comment by ricar2ce** [comment]
OK, thanks you very much.
