### ISSUE TITLE
Redering login widgets breaks login and register views

### ISSUE THREAD

**Issue by Eseperio** [2amigos/yii2-usuario#86]
### What steps will reproduce the problem?
Add `echo \Da\User\Widget\LoginWidget::widget([]);` to the main layout.
Then try to access `user/security/login` or `user/security/register`
### What is the expected result?
Login page should be visible.
### What do you get instead?
Exception. View not found.
`...vendor/2amigos/yii2-usuario/src/User/resources/views/widgets/login.php`

An strange behavior happens. Login view is under `.../views/widgets/login/login.php`, and it works perfect until you render the widget on your own view, when then yii search the view as `.../views/widgets/login.php`. Notice the abscence of `login` folder.
As a clue, in yii2-user it doesn´t happen.

**Comment by tonydspaniard** [comment]
@Eseperio The problem is that you are using the widget *outside* of the user module, which means that the actual path of the views is wrong as it first looks inside its folder (which it doesn't exist) and then looks within your configured view path (your application's view path, which doesn't exist as you didn't override the file). 

In order to make it work you have to 'override' the views or configure the `components::view::theme::pathMap`: https://github.com/yiisoft/yii2/blob/master/docs/guide/output-theming.md

**Comment by tonydspaniard** [comment]
@Eseperio do you mind sharing your code so I can mimic the scenario? I'll review it personally. Thank you for your time.

**Comment by Eseperio** [comment]
Is a clean project. 

This is what i have:

In: **layouts/main.php**

Just before `body` close tag.
`echo \Da\User\Widget\LoginWidget::widget([]);`
The access `site/index`


You´ll get a View not found exception because context is not the same as module. Ok. Let´s map module views. `@Da/...ces/views=>@app/views/user` 

Now, the expected widget view route should be 
`@app/views/user/widgets/login/login.php`.
But it is (on `site/index`)
 `@app/views/widgets/login/login.php`.

And in `SecurityController` actions is this one:
`@Da/User/resources/views/widgets/login.php`

Well, if you put the overrided view under `@app\views\widgets\login.php` everything works ok until you execute any of the module actions.

Is too strange, because it is like pathMap ignoring login subfolder when it is in a context different than it´s own module.

**Comment by tonydspaniard** [comment]
I'll check it... Thanks for your time @Eseperio

**Comment by tonydspaniard** [comment]
@Eseperio you were totally right. The widget has been fixed by providing a full path with alias on the widget. Works now out of the box but if you wish to override its view, simply set 'view' as:

```php 
'components' => [
 // ...
    'view' => [
          'theme' => [
        'pathMap' => [
            '@Da/User/resources/views/' => '@app/views/user/'
        ]
    ]
    ]
]

**Comment by Eseperio** [comment]
OK. One more thing. I´ve seen that widget is not used within the module. So is a complement. It should be described at least in documentation so anyone knows it exists.

**Comment by tonydspaniard** [comment]
@Eseperio I agree. Thanks.
