### ISSUE TITLE
Error running migration using --migrationPath="@Da/User/Migration"

### ISSUE THREAD

**Issue by PaulKish** [2amigos/yii2-usuario#87]
### What steps will reproduce the problem?
Running `./yii migrate --migrationPath="@Da/User/Migration"`

### What is the expected result?
Yii migration running successfully

### What do you get instead?
Exception 'Error' with message 'Class 'm000000_000001_create_user_table' not found'

This is occurring on the Yii2 advanced app, Yii version 2.0.12. The migration however run successfully using the second way of so the documentation probably needs updating or a bug

**Comment by tonydspaniard** [comment]
@PaulKish I'll have a look. Thanks for your time.

**Comment by tonydspaniard** [comment]
@PaulKish definitely is an doc issue. Updating.
