### ISSUE TITLE
Migration guide from dektrium's tools

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#9]
It would be nice to have a wiki or doc page which explains how to migrate a project from the existing Dektrium's tools to this module

**Comment by tonydspaniard** [comment]
@maxxer I will write that. Thanks for suggestion.

**Comment by tonydspaniard** [comment]
@maxxer I have been checking the features that dektrium tools have, and unfortunately, there are a couple  of missing parts that need to be included for a proper and complete migration: 

- impersonation 
- send password via email from admin (but that something I would not include at all as I really think is a security issue) 
- allow user to delete their own account 

Once impersonation and user own account removal is included, then I could write a complete migration guide. I have add those points as part of a milestone, so is being planned.

**Comment by maxxer** [comment]
I had more the idea of a pure technincal document, explaining what's needed to do in *composer.json*, routes/views to fix, and so on, something like that.

As for the (yet) missing features they could just be stated in the migration guide.

**Comment by tonydspaniard** [comment]
@maxxer ok, you convinced me. I'll do it asap.

**Comment by maxxer** [comment]
I'll be happy to help deliver this guide, but I still have to start seriously looking into the extension... If you can write the composer part I'll try to do the matching of the routes

**Comment by tonydspaniard** [comment]
>  If you can write the composer part I'll try to do the matching of the routes

I'll do... In fact, I did it with one of our projects last week. I just need to find the time to start. Thank you for your offer.

**Comment by tonydspaniard** [comment]
@maxxer on master: https://github.com/2amigos/yii2-usuario/blob/master/docs/installation/available-actions.md

**Comment by mrbig00** [comment]
Any news on this?

I'm asking this because I need to migrate a project in the next few days, and I can start at least a draft version for a migration guide.

**Comment by tonydspaniard** [comment]
I am not able currently. If you can help that would be awesome, I can assign this issue to you if you want.

The guide should follow the format within the docs folder.

**Comment by tonydspaniard** [comment]
hey @mrbig00 will you be able to do it or should I write it my self? I have currently added many features and closed 1.1 milestone (I still need to test the new features like reCaptcha). Would be awesome if I could include the migration guide prior to launch new version.

**Comment by maxxer** [comment]
sorry guys, I proposed as well but I'm not having much spare time lately

**Comment by tonydspaniard** [comment]
Not a problem @maxxer I'll do my best to do it throughout these days.

**Comment by maxxer** [comment]
We should document the corresponding implementation of dektrium's [config params](https://github.com/dektrium/yii2-user/blob/master/docs/configuration.md) (if present)

**Comment by tonydspaniard** [comment]
@maxxer Thanks. Nevertheless, I am currently highly busy these days. I won't be able to do the migration guide. Practically impossible. Apologies.

**Comment by tonydspaniard** [comment]
done by #144 (Thanks @maxxer)
