### ISSUE TITLE
Cache AuthDbManagerComponent results to reduce sql queries?

### ISSUE THREAD

**Issue by jkmssoft** [2amigos/yii2-usuario#96]
Cache AuthDbManagerComponent results to reduce sql queries?
Example: https://github.com/letyii/yii2-rbac-cached/blob/master/RbacCached.php

**Comment by tonydspaniard** [comment]
@jkmssoft 
The component it extends from `DbManager` and its properties states: 

```php 
    /**
     * @var Cache|array|string the cache used to improve RBAC performance. This can be one of the following:
     *
     * - an application component ID (e.g. `cache`)
     * - a configuration array
     * - a [[\yii\caching\Cache]] object
     *
     * When this is not set, it means caching is not enabled.
     *
     * Note that by enabling RBAC cache, all auth items, rules and auth item parent-child relationships will
     * be cached and loaded into memory. This will improve the performance of RBAC permission check. However,
     * it does require extra memory and as a result may not be appropriate if your RBAC system contains too many
     * auth items. You should seek other RBAC implementations (e.g. RBAC based on Redis storage) in this case.
     *
     * Also note that if you modify RBAC items, rules or parent-child relationships from outside of this component,
     * you have to manually call [[invalidateCache()]] to ensure data consistency.
     *
     * @since 2.0.3
     */
    public $cache;
    /**
     * @var string the key used to store RBAC data in cache
     * @see cache
     * @since 2.0.3
     */
    public $cacheKey = 'rbac';
```

The only place where I think it should be enhanced is on `getAssignments` and modify properly the `InvalidateCache()` function. Knowing the memory implications. Anybody else thinks is a good idea?

**Comment by schmunk42** [comment]
I had to configure it like so:

```
    'container' => [
        'definitions' => [
            \Da\User\Component\AuthDbManagerComponent::class => [
                'cache' => 'cache'
            ]
        ],
    ],
```

because `initAuthManager` from https://github.com/2amigos/yii2-usuario/blob/master/src/User/Bootstrap.php#L207 completely overrides our configuration from `authManager`. Is this an expected behavior with DI? 

CC: @cebe @handcode @eluhr

**Comment by cebe** [comment]
It should only be overwritten, if your instance is not implementing `AuthManagerInterface`. If you change the class, the config can not be kept obviously because it may not match the new class.
